### ISSUE TITLE
Value-binding is not working as expected. Why?

### ISSUE THREAD

**Issue by shmigandrew** [doctrine/doctrine2#7166] opened 2018-03-31 07:37 UTC
I am using Symfony 3.4.6 + Doctrine - these are my main "tools".

Two identical queries written in MySQL give different results. Why? I don't know. Hope someone will help me.

This code gives an error:
```
' with params [134, ["system"], "2018-02-28 21:24:47", "2018-03-30 21:24:47"]:
Notice: Array to string conversion
```

```php
public function history(User $user, \DateTime $from, \DateTime $to,
                            array $type = [PaymentTransaction::PAYMENT_TRANSACTION_TYPE_SYSTEM,
                                PaymentTransaction::PAYMENT_TRANSACTION_TYPE_PARTNERSHIP,
                                PaymentTransaction::PAYMENT_TRANSACTION_TYPE_PERSONAL]): array
    {
        $connection = $this->getEntityManager()->getConnection();
        $result = $connection->fetchAll('
        SELECT payment_transaction.*, `user`.`first_name` as `user_first_name`, `user`.`last_name` as `user_last_name`, `user`.`email` as `user_email`
        FROM payment_transaction
        LEFT JOIN `user` ON `user`.`id` = payment_transaction.from_id
        WHERE payment_transaction.to_id = :user
              AND payment_transaction.type IN (:types)
              AND payment_transaction.registered_at >= :from
              AND payment_transaction.registered_at <= :to
        ORDER BY payment_transaction.id DESC
        ', [
            "user" => $user->getId(),
            "from" => $from->format("Y-m-d H:i:s"),
            "to" => $to->format("Y-m-d H:i:s"),
            "types" => $type,
        ], [
            \PDO::PARAM_INT,
            \PDO::PARAM_STR,
            \PDO::PARAM_STR,
            Connection::PARAM_STR_ARRAY,
        ]);

        return $result;
    }
```

The query is working after replacing placeholders with ```?``` signs. 
The question still remains - WHY it's not working with ```:name```-placeholders?

No answers on StackOverflow... maybe a bug?
https://stackoverflow.com/questions/49579833/value-binding-is-not-working-as-expected-why

**Comment by Ocramius** [comment] 2018-03-31 17:15
This seems to be a DBAL-only issue (no ORM involved).

It looks to me that you are binding parameters with `PDO` constants.
First of all, don't use PDO's types, but DBAL types:

https://github.com/doctrine/dbal/blob/46069b6bc84b0f41733a23d3b56e2774d0502c94/lib/Doctrine/DBAL/Types/Type.php#L37-L61

Few things to do here:

 1. we need a test case to reproduce the issue (if it is a DBAL) bug
 2. report it to https://github.com/doctrine/dbal

Meanwhile, I'm closing here, as the ORM is not involved.

**Closed by Ocramius** 2018-03-31 17:15 UTC

**Comment by shmigandrew** [comment] 2018-03-31 18:59
@Ocramius , after changing to DBAL types everything went OK. Thank you!

**Comment by shmigandrew** [comment] 2018-04-13 09:06
I assume there is no `INT` version in DBAL types, that's why `Connection::PARAM_INT_ARRAY` makes query return correct results.

**Comment by Ocramius** [comment] 2018-04-13 10:39
Yeah, this is indeed for `Connection::PARAM_INT_ARRAY`. @morozov and @Majkl578 are working on a better spec for making parameter binding type-safe: consider reviewing https://github.com/doctrine/dbal/pull/3010 yourself and helping out on it based on your current (unpleasant) experience
