### ISSUE TITLE
Querying large number of entities via primary key criteria

### ISSUE THREAD

**Issue by yasminalzokari** [doctrine/doctrine2#6452] opened 2017-05-19 11:14 UTC
We have a problem querying a large number (i.e. more than 1000) of entities via criteria on their primary key which fields due to expanding list parameters with more than 1000 expressions, i.e. it yields the Oracle error
```
ORA-01795: maximum number of expressions in a list is 1000
```

We would have expected that DBAL takes care of this, but it looks like this is [considered to much of a corner case](https://github.com/doctrine/dbal/pull/2699#issuecomment-294801322). Hence we tried too implement a workaround on the repository level by issuing several calls to the underlying repositories `findBy` method and merging their results after chunking up the list parameters, e.g.:
```
public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
{
    $repository = $this->getRepository();
    return self::chunkListParameters($criteria, function ($clause) use ($repository, $orderBy, $limit, $offset) {
        return $repository->findBy($clause, $orderBy, $limit, $offset);
    });
}

private static function chunkListParameters(array $criteria, callable $query, $size = 1000)
{
    $clauses = [[]];
    $newClauses = [];
    foreach ($criteria as $parameter => $values) {
        foreach ($clauses as $clause) {
            if (is_array($values) && count($values) > $size) {
                foreach (array_chunk($values, $size) as $chunk) {
                    $newClause = $clause;
                    $newClause[$parameter] = $chunk;
                    $newClauses[] = $newClause;
                }
            } else {
                $clause[$parameter] = $values;
                $newClauses[] = $clause;
            }
        }
        $clauses = $newClauses;
        $newClauses = [];
    }

    if (count($clauses) == 1) {
        return $query($clauses[0]);
    } else {
        return array_reduce(array_map($query, $clauses), "array_merge", []);
    }
}
```

Do think that something like this could become part of the upstream implementation?

**Comment by Ocramius** [comment] 2017-05-20 10:49
Closing as duplicate of https://github.com/doctrine/dbal/pull/2699

**Closed by Ocramius** 2017-05-20 10:49 UTC
