### ISSUE TITLE
doctrine:generate:entities *-to-Many

### ISSUE THREAD

**Issue by DonCallisto** [doctrine/doctrine2#6007] opened 2016-09-07 09:39 UTC
Why `doctrine:generate:entities` will produce a setter (in `*-to-Many` relationship) with a `ArrayCollection` in type hinting instead of `Collection` (interface)?

I've noticed that, sometimes, a getter on collection (so something handled by doctrine) could return `PersistentCollection` instead of `ArrayCollection` and if I use a setter with returned value, an exception will be raised (of course).

What do you guys think?

**Comment by Ocramius** [comment] 2016-09-07 20:03
> Why `doctrine:generate:entities` will produce a setter (in `*-to-Many` relationship) with a `ArrayCollection` in type hinting instead of `Collection` (interface)?

Switching it to `Collection` is fine: feel free to send a PR :-)

**Comment by DonCallisto** [comment] 2016-09-07 21:09
Maybe I got an outdated version because now that I've tried to start a PR from master, and generated entity methods, I get

```
<?php

namespace Vendor\Bundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="bar")
 * @ORM\Entity()
 */
class Bar
{
    /**
     * @ORM\OneToMany(targetEntity="Vendor\Bundle\Entity\Bar", mappedBy="bar")
     */
    protected $foos;

    /**
     * Constructor
     */
    public function __construct()
    {
        // This is fine
        $this->foos = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add foo
     *
     * @param \Nuvola\AppBundle\Entity\Bar $foo
     *
     * @return Bar
     */
    public function addFoo(\Nuvola\AppBundle\Entity\Bar $foo)
    {
        $this->foos[] = $foo;

        return $this;
    }

    /**
     * Remove foo
     *
     * @param \Nuvola\AppBundle\Entity\Bar $foo
     */
    public function removeFoo(\Nuvola\AppBundle\Entity\Bar $foo)
    {
        $this->foos->removeElement($foo);
    }

    /**
     * Get foos
     *
     * @return \Doctrine\Common\Collections\Collection <--- This is fine too
     */
    public function getFoos()
    {
        return $this->foos;
    }
}
```

Which seems perfectly fine.

What I notice here is that for `*toMany` there is no `setter` method: is it fine to have only `add` and `remove` methods (along with `get` of course)?. 

If so, you can close this as it's not a bug or real issue.

**Comment by Ocramius** [comment] 2016-09-07 21:13
Closing, not a bug indeed then. Also, setting entire collections is problematic, so it is better that it is gone from the generator :-)

**Closed by Ocramius** 2016-09-07 21:13 UTC
Labels: Bug, Invalid, Missing Tests
