### ISSUE TITLE
findAll doesn't return all the records

### ISSUE THREAD

**Issue by assoum891** [doctrine/doctrine2#5617] opened 2016-01-18 14:06 UTC
when i do findAll on my entity repository i just get the first record of the database although i have two records in the database, but when i override the findAll method into my repo and i create the query with all the 'leftjoins' of my relations i get all the records...

**Comment by Jean85** [comment] 2016-01-18 14:55
Can you give us a reproducible case, or at least some of your code?

**Comment by assoum891** [comment] 2016-01-19 09:32
Actually i have an entity called Offer that has oneToMany relations with an entity called Account, when i call findAll() on my repository class it just returns the first record of the database but when i override the method and do this 
<pre>
public function findAll()
    {
       return $this->createQueryBuilder('o')
            ->select('o, sa, sda, a')
            ->leftJoin('o.sponsorAccount', 'sa')
            ->leftJoin('o.sponsoredAccount', 'sda')
            ->leftJoin('o.account', 'a')
            ->getQuery()
            ->getResult();
    }
</pre>
i get all the records.

**Comment by Jean85** [comment] 2016-01-19 09:39
What if you remove the others joins? (sponsorAccount, sponsoredAccount)
Are you sure about your relations? The Doctrine schema is valid?

**Comment by assoum891** [comment] 2016-01-19 09:49
I don't think there is something wrong with my schema, 
<pre>
     /**
     * @var Account
     * @ORM\ManyToOne(targetEntity="AccountNamespace...")
     * @ORM\JoinColumn(name="account_id", referencedColumnName="id", nullable=false)
     */
    protected $account;

    /**
     * @var Account
     * @ORM\ManyToOne(targetEntity="AccountNamespace...")
     * @ORM\JoinColumn(name="sponsored_account_id", referencedColumnName="id", nullable=true)
     */
    protected $sponsoredAccount;

    /**
     * @var Compte
     * @ORM\ManyToOne(targetEntity="AccountNamespace...")
     * @ORM\JoinColumn(name="sponsor_account_id", referencedColumnName="id", nullable=true)
     */
    protected $sponsorAccount;
</pre>

I've just tried removing the joins of sponsorAccount and sponsoredAccount, still one result in the list view...

**Comment by Jean85** [comment] 2016-01-19 10:02
Ok, you have a ManyToOne, not a OneToMany as you stated in your previous comment. That's what was throwing me off.

Can you try this implementation? What happens with this?

    public function findAll()
    {
       return $this->createQueryBuilder('o')
            ->join('o.account', 'a')
            ->getQuery()
            ->getResult();
    }

**Comment by assoum891** [comment] 2016-01-19 10:06
oh sorry i meant manyToOne, and yes i tried that, i still don't get all the records in my list

**Comment by Jean85** [comment] 2016-01-19 10:22
So that's your problem: you have a discrepancy between your schema and your database. The `findAll()` assumes that your join is not nullable (as from your definition) and does a JOIN instead of a LEFT JOIN as you're doing.

If you check your DB, you probably have 1 Offer with a NOT NULL on account_id, and the others with null.

You can close this issue.

**Comment by assoum891** [comment] 2016-01-19 10:42
I dont understand.. actually the account is not supposed to be null, it's a mandatory information and all the records have not null account_id values, it's the sponsored_account_id and sponsor_account_id columns that can be null..and even the first record returned when i do just findAll() have a null sponsor_account_id

**Comment by Jean85** [comment] 2016-01-19 10:53
I reduced your problem to this difference:
With this, you do a LEFT JOIN (like you did before), and you should obtain all the offers:

    public function findAll()
    {
       return $this->createQueryBuilder('o')
            ->leftJoin('o.account', 'a')
            ->getQuery()
            ->getResult();
    }

With this (my suggestion), you do a INNER JOIN, like the native `findAll()` is doing, and you are retrieving just one row.

    public function findAll()
    {
       return $this->createQueryBuilder('o')
            ->join('o.account', 'a')
            ->getQuery()
            ->getResult();
    }

The join is the only change, so the problem is in the join definition. If you're sure that all your rows in you offer table have a not null value on that field, you could check your inverse relation definition.

**Comment by Ocramius** [comment] 2016-01-20 14:44
I initially thought this was about the ORM's provided `Doctrine\ORM\EntityRepository#findAll()` API, but that's not the case.

Therefore closing as `Invalid`: this is not a bug.

**Closed by Ocramius** 2016-01-20 14:44 UTC
Labels: Invalid

**Comment by GreeKatrina** [comment] 2017-03-20 16:15
I ran into this issue [as well](http://stackoverflow.com/questions/30941836/doctrine-not-finding-data-on-google-app-engine?noredirect=1&lq=1).

In my case, the User's company_id was either 0 or an id of a Company that didn't exist in the db (I don't remember which). I don't actually "require" the company_id, it can be 0 if the User doesn't belong to a company. 

1. Is there a way to say that the company_id cannot be null, but is not required (as in, do a left instead of an inner join)?

2. I'm sure many people will be using Doctrine for existing DBs that don't have clean data (ex: a User's company_id doesn't exist in the company table). Should they expect an empty result for queries that fit this criteria?

**Comment by Ocramius** [comment] 2017-03-20 16:23
> I'm sure many people will be using Doctrine for existing DBs that don't have clean data (ex: a User's company_id doesn't exist in the company table). Should they expect an empty result for queries that fit this criteria?

Use an SQL filter. Also, check https://stackoverflow.com/questions/15502408/doctrine-2-use-default-0-values-instead-of-null-for-relation

**Comment by GreeKatrina** [comment] 2017-03-20 18:57
In the [BasicEntityPersister](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php) class and the `getJoinSQLForJoinColumns()` method, would it be possible to add a "required" check or something like this?

```php
User
/**
 * @ManyToOne(targetEntity="Company", inversedBy="users", fetch="EAGER")
 * @JoinColumn(name="company_id", referencedColumnName="company_id", nullable=false, required=false)
 */
private $company;

BasicEntityPersister
/**
 * Generates the appropriate join SQL for the given join column.
 *
 * @param array $joinColumns The join columns definition of an association.
 *
 * @return string LEFT JOIN if one of the columns is nullable, INNER JOIN otherwise.
 */
protected function getJoinSQLForJoinColumns($joinColumns)
{
    // if one of the join columns is nullable, return left join
    foreach ($joinColumns as $joinColumn) {
         if ( ! isset($joinColumn['nullable']) || $joinColumn['nullable'] 
         || ( ! isset($joinColumn['required']) || ! $joinColumn['required'] )) {
             return 'LEFT JOIN';
         }
    }
    return 'INNER JOIN';
}
```

From the docs it defines `nullable` under the [@Column](http://doctrine-orm.readthedocs.io/en/latest/reference/annotations-reference.html#annref-column) annotation as:

> **nullable:** Determines if NULL values allowed for this column.

But under [@JoinColumn](http://doctrine-orm.readthedocs.io/en/latest/reference/annotations-reference.html#joincolumn) it takes on a second "required" meaning:

> **nullable:** Determine whether the related entity is required, or if null is an allowed state for the relation. Defaults to true.

I think it makes more sense to keep `nullable` defined the same for `@Column` and `@JoinColumn`, and then add a second option (`required`) to `@JoinColumn`.

> **nullable:** Determines if NULL values allowed for this column. Defaults to true.
> **required:** Determines whether the related entity is required, or if null is an allowed state for the relation. Defaults to false.

-------------------

It seems like this may already be possible after reading the docs on `columnDefinition`, but I'm not sure how to use it and how the overriding works:

> Using this attribute on `@JoinColumn` is necessary if you need slightly different column definitions for joining columns, for example regarding NULL/NOT NULL defaults. However by default a “columnDefinition” attribute on `@Column` also sets the related `@JoinColumn`’s columnDefinition.

**Comment by lcobucci** [comment] 2017-03-20 22:33
@GreeKatrina although an ORM can be used on applications that don't have clear data it shouldn't be designed with that intent.

A `nullable` association is an optional one and that's how doctrine manages that. Adding `required` adds complexity for no good reason (since well designed schemas will have consistent data). 

What I'd do in your case is create a new nullable column (with a proper FK), migrate the data that can be migrated without causing an constraint error and then start using it consistently. Just drop the old column when you're sure it's no longer relevant.

**Comment by Ocramius** [comment] 2017-03-21 06:48
You can poke at it as much as you like, but such an atrocity is not landing
in the ORM anytime.
Use NULL where it is supposed to be used: it is a fair assumption and it
will not lead yo further complications.
You can make the ORM compatible with your older code via writable views and
triggers instead (proper BC and FC approach).

**Comment by GreeKatrina** [comment] 2017-03-21 15:09
@lcobucci @Ocramius Fair enough. Is it possible to set nullable to true for `@JoinColumn`, and then do something with `columnDefinition` that forces something like `company_id IS NOT NULL`? I wasn't sure if that's what it meant in the docs by "slightly different column definitions for joining columns, for example regarding NULL/NOT NULL defaults".

**Comment by Ocramius** [comment] 2017-03-21 15:41
@GreeKatrina that is possible, but it will still crash the ORM during load operations (due to failed association traversal - `NULL` means something very specific to the ORM).
