### ISSUE TITLE
Duplicate property id for entries of a inherited table (Doctrine ORM "JOINED" inheritance)

### ISSUE THREAD

**Issue by ggirodda** [doctrine/doctrine2#6484] opened 2017-06-02 07:39 UTC
| Q                | A
| ---------------- | -----
| Symfony version  | 3.2.9
| Doctrine ORM  | 2.5.6

Hi,
I'm using doctrine "joined" table inheritance, using the annotations in this way
```php
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="joined_type",  type="string")
```
Everything wotks fine when I create the entries, but when I try to get results from database with a simple findAll(), I get a duplicated property id for the entries of the inherited type, in this case "MoreText":
![response](https://cloud.githubusercontent.com/assets/12408871/26715142/cc39e6aa-4774-11e7-94b7-1b4372f4badb.jpg)

I'm not really expert but I just followed the doctrine documentation for table inheritance, and this is not the first time I use it, so I think that it can be a bug.

Thank you

**Comment by Ocramius** [comment] 2017-06-02 07:40
This is most likely a problem to be reported in https://github.com/symfony/symfony as a var-dumper component bug.

Duplicate properties do not exist at engine level, so the var-dumper is doing something weird here.

**Comment by ggirodda** [comment] 2017-06-02 07:47
Hi,
Thank you for your answer. I think that is not a var-dumper bug, I put the dumped response just to show the problem. When I try to get the property id I get a message telling me that the id property is null :

> An exception has been thrown during the rendering of a template ("Parameter "id" for route "admin_more_show" must match "[^/]++" ("" given) to generate a corresponding URL.").

The exception in this case is in twig, because I try to access a property id wich is not a number

**Comment by ggirodda** [comment] 2017-06-02 07:52
I posted the issue on symfony bug report too, but they told me that is a doctrine issue.
https://github.com/symfony/symfony/issues/23029

**Comment by Ocramius** [comment] 2017-06-02 08:00
> The exception in this case is in twig, because I try to access a property id wich is not a number

A script to reproduce the issue is needed. Re-opening here until we decide who's "responsible" :-)

**Comment by Ocramius** [comment] 2017-06-07 22:03
As per symfony/symfony#23029, a private `id` property was defined twice in the inheritance tree: this is unsupported, but should have been caught by schema validation. @ggirodda can you please check what the schema validation says about it (the CLI command)?

**Comment by ggirodda** [comment] 2017-06-08 05:18
The schema validation doesn't catch the error:
[Mapping]  OK - The mapping files are correct.

**Comment by Ocramius** [comment] 2017-06-08 06:59
Yeah, so the property is probably un-mapped...

**Comment by ggirodda** [comment] 2017-06-08 07:43
Yes, because when I try to do a doctrine:schema:update if I put or delete the property id from inherited entity nothing changes, the command tell me that there are no changes

**Comment by Ocramius** [comment] 2017-06-22 02:48
Thought about this one some more, and I'm going to close it as `invalid`.

To recap:

 * a private property `id` was defined in a parent class `A`
 * a private property `id` was defined in a child class of `A`, called `B`
 * `A#$id` was mapped
 * `B#$id` was not mapped

Therefore this is expected behavior.

We can possibly add exceptions and error messages for this scenario, but it's not going to be happening in the future.
Specifically, Doctrine ORM does not support properties with the same name in an inheritance tree: it was never designed to do it.

**Closed by Ocramius** 2017-06-22 02:48 UTC
Labels: Bug, Missing Tests
