### ISSUE TITLE
Allow ORM 2.5 to work with Common 2.7

### ISSUE THREAD

**Issue by BenMorel** [doctrine/doctrine2#6176] opened 2016-12-18 12:52 UTC
`doctrine/orm` currently requires:

    "doctrine/common": ">=2.5-dev,<2.7-dev"

Is there any reason why it's not allowed to work with `doctrine/common: 2.7`? This version adds support for PHP 7 and PHP 7.1 in proxy generation.

If I try to force `doctrine/common: 2.7.*` in my composer.json, I get downgraded to `doctrine/orm: 2.4.8` and `doctrine/dbal: 2.4.5`, which seems a bit of a nonsense.

**Comment by Ocramius** [comment] 2016-12-18 12:56
Duplicate of #6157

We are keeping the dependency ranges on short leash due to tight coupling between these libraries (they were split from a single core, after all), so BC breaks are likely.

This may change with new major versions, but not for now.

**Closed by Ocramius** 2016-12-18 12:56 UTC

**Comment by BenMorel** [comment] 2016-12-18 13:12
Thanks for the fast reply. Yet you merged #6156 in the `2.5` branch, does that mean we can expect `2.5.6` to be released soon with this change?

**Comment by Ocramius** [comment] 2016-12-18 13:44
Ya

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by BenMorel** [comment] 2016-12-20 21:50
Thanks for the ORM 2.5.6 release! Any ETA for DBAL 2.5.6, by any chance?

**Comment by Ocramius** [comment] 2016-12-23 01:35
Will try going through the queue for DBAL on the 25th, but no promises.

**Comment by BenMorel** [comment] 2016-12-23 11:28
That would be great, thanks for the update!
