### ISSUE TITLE
Hydrating  with `enumType` as array gives *string* instead of Enum (DQL with join)

### ISSUE THREAD

**Issue by mzk** [doctrine/doctrine2#10031] opened 2022-09-06 15:38 UTC
### Bug Report

When I have a query:
```
return $this->entityManager->createQuery('SELECT o.orderStatus FROM Entity\Order o')
            ->getResult(AbstractQuery::HYDRATE_ARRAY);
```
Then `$result[0]['orderStatus']` is instance of BackendEnum OrderStatus.

But when I have a query:
```
return $this->entityManager->createQuery('SELECT o FROM Entity\Order o')
            ->getResult(AbstractQuery::HYDRATE_ARRAY);
```
Then `$result[0]['orderStatus']` is simple string.

Our Order entity field:
```
    #[Column(type: Types::STRING, nullable: false, enumType: OrderStatus::class, options: ['charset' => 'utf8', 'collation' => 'utf8_unicode_ci'])]
    private OrderStatus $orderStatus;
```

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.13.1

#### Summary

It should be the same result for both cases. 

#### Current behavior

`SELECT o` retuns string, `SELECT o.orderStatus` returns the BackendEnum

#### How to reproduce

Use entity as [described](https://www.doctrine-project.org/2022/01/11/orm-2.11.html) and fetch from query builder as an array.

#### Expected behavior
`SELECT o` returns an array that contains BackendEnum.

for ref: https://github.com/doctrine/orm/issues/9622

**Comment by michnovka** [comment] 2022-09-11 22:11
I generally try to avoid Array Hydration, but I agree that this should work nonetheless. If you use standard object hydration (default) is there any issue?

**Comment by mzk** [comment] 2022-09-12 07:05
The default object hydration works fine.

**Comment by janedbal** [comment] 2022-09-12 13:49
The biggest issue I see here is the same reasoning I wrote in #9622:

> **Migrating from enums used as custom types to this native form is impossible as it behaves differently**

**Comment by derrabus** [comment] 2022-09-22 07:04
Duplicate of #9947

**Closed as completed by derrabus** 2022-09-22 07:04 UTC
