### ISSUE TITLE
"The query returned a row containing multiple columns." using HYDRATE_SINGLE_SCALAR with a hidden column

### ISSUE THREAD

**Issue by Cartman34** [doctrine/doctrine2#9209] opened 2021-11-29 19:27 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.10.1

#### Summary

While trying to get a list of ID for one entity, I tried to use `getResult(AbstractQuery::HYDRATE_SINGLE_SCALAR)`, one column is visible, the other is hidden, it seems an issue for Doctrine but it should work.

#### Current behavior

Doctrine throws exception about multiple column selected while using HYDRATE_SINGLE_SCALAR but only one is visible, the other is hidden.
The error is

> The query returned a row containing multiple columns. Change the query or use a different result function like getScalarResult().

#### How to reproduce

Select 2 columns, one visible, other is hidden.
Get a list of first column, using `getResult(AbstractQuery::HYDRATE_SINGLE_SCALAR)`

$qb->select('entity.id AS id');
$qb->select('entity.id AS HIDDEN otherId');
$idList = $qb->getQuery()->getResult(AbstractQuery::HYDRATE_SINGLE_SCALAR);

#### Expected behavior

I get a list of IDs with no error.

**Comment by greg0ire** [comment] 2021-11-30 13:01
Please upgrade, version 2.10 is no longer supported. If you experience the bug in 2.13, let me know and I will reopen this.

**Comment by greg0ire** [comment] 2021-11-30 13:02
Can you please provide a stack trace? Read more on how to do so here: https://symfony.com/doc/current/contributing/code/stack_trace.html

**Comment by Cartman34** [comment] 2021-11-30 15:55
Is that you want ?

> Doctrine\ORM\NonUniqueResultException:
> The query returned multiple rows. Change the query or use a different result function like getScalarResult().
> 
>   at vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SingleScalarHydrator.php:32
>   at Doctrine\ORM\Internal\Hydration\SingleScalarHydrator->hydrateAllData()
>      (vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php:268)
>   at Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll(object(Result), object(ResultSetMapping), array())
>      (vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:1169)
>   at Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(null, 4)
>      (vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:1115)
>   at Doctrine\ORM\AbstractQuery->execute(null, 4)
>      (vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:863)
>   at Doctrine\ORM\AbstractQuery->getResult(4)
>      (src/Controller/ServiceSearchController.php:184)

**Comment by greg0ire** [comment] 2021-11-30 22:17
Yes, exactly 👍

**Comment by greg0ire** [comment] 2021-11-30 22:19
So the exception comes from here: https://github.com/doctrine/orm/blob/15ec77fa79130ad5bbcb20f0630bc43d48c0436d/lib/Doctrine/ORM/Internal/Hydration/SingleScalarHydrator.php#L32 and … oh!

Duplicate of #4257 , right?

**Comment by greg0ire** [comment] 2021-11-30 22:20
Duplicate of #4257

**Comment by greg0ire** [comment] 2021-11-30 22:22
Reopening since #4257 is supposed to be fixed… @Mediagone maybe you can help with this?
@Cartman34 you will find a test case in #8340, you can maybe copy/paste/adapt it to add something that looks like what you have, thus creating a failing test case?

**Comment by Mediagone** [comment] 2021-12-01 13:22
How can I know the target version into which the fix was merged?

**Comment by greg0ire** [comment] 2021-12-01 14:29
1. find the PR
2. find the commit in the PR
3. the commit page on Github shows that kind of information

Here we can see that it was merged in 2.7: https://github.com/doctrine/orm/commit/d83c0a6b6cb915b5066cf32d2aab7700d6593421 , but weirdly, it does not show tag information

It looks like your commit was merged in 2.7, but should have been merged in 2.7.x. I'm closing this and reopening the other issue then.

**Closed as completed by greg0ire** 2021-12-01 14:29 UTC
