### ISSUE TITLE
Generate entities for all schemas of a Oracle database

### ISSUE THREAD

**Issue by globtec** [doctrine/doctrine2#5991] opened 2016-08-24 17:20 UTC
I have a problem in a legacy system that use Oracle database with many schemas. I’ve added the Doctrine2 to Project. When I used the features to generate entities, I saw that the generated entities was only of one of the username’s schemas in the connection. How to generate entities for all schemas used in my application? The user used in the connection with database has a privilege in all schemas and the database has sinonimos configured.

**Comment by Ocramius** [comment] 2016-08-24 17:21
Only the schema you are currently working on is considered by the database driver: this is by design.

Closing as `can't fix`.

**Closed by Ocramius** 2016-08-24 17:21 UTC
