### ISSUE TITLE
Unnecessary queries for updating

### ISSUE THREAD

**Issue by trsteel88** [doctrine/doctrine2#5594] opened 2016-01-07 03:53 UTC
I'm not sure if this is by design. However, I've noticed that if you have a decimal and store it as a float, Doctrine will run a MySQL query unnecessarily for certain values.

e.g.

ProductModel.php
```php
...
/**
     * Set price.
     *
     * @param float $price
     *
     * @return $this
     */
    public function setPrice($price)
    {
        $this->price = (float) $price;

        return $this;
    }
...

Code:
```php

$product->setPrice('10.20');
$product->setPrice(10.20);
```

For both examples above, (float) will remove the zero from the end. This results in "10.2". Since the value within the database is '10.20', Doctrine executes an UPDATE query even though nothing has changed.

Is this by design so values don't need to be checked and reduce overhead?

**Comment by Ocramius** [comment] 2016-01-07 03:54
@trsteel88 something else is happening here, in my opinion. Could you dump the entity diffs from a `UnitOfWork`? Can you reproduce this in a test case scenario?

**Comment by zeroedin-bill** [comment] 2016-01-07 03:55
@Ocramius could be because some drivers return float/real/decimal as string and some don't.

**Comment by trsteel88** [comment] 2016-01-07 03:56
A dump of the UnitOfWork for an entity is:

```php
array:2 [
  "price" => array:2 [
    0 => "289.00"
    1 => 289.0
  ]
]
```

**Comment by Ocramius** [comment] 2016-01-07 03:58
> @Ocramius could be because some drivers return float/real/decimal as string and some don't.

Ah yes, indeed. I was thinking that we were discussing fresh entities flushed multiple times.
Floating point values (entities with values mapped as `numeric`) will store the values as `string` inside your entities, therefore a `(float)` cast changes the type, and therefore the value is not the same anymore.

This is expected behavior: you are supposed to map the value as a `string` inside your mappings, or to use a custom DBAL type if you trust a `(float)` cast enough :-) 

Closing as `can't fix`.

**Closed by Ocramius** 2016-01-07 03:58 UTC
Labels: Bug, Can't Fix, Missing Tests

**Comment by trsteel88** [comment] 2016-01-07 04:01
Ah got it. Thanks for clarifying. I thought Doctrine would normalize the decimal before adding it to the changeset since it knows the precision/scale of the Decimal.

**Comment by Ocramius** [comment] 2016-01-07 04:02
@trsteel88 we can't really convert numeric values in PHP due to the risk of a lossy cast :-\ If a `(float)` just cuts it for your use-case, then I suggest you use that, but the tool is indeed used also for monetary transactions, and you don't want to see problems there, heh...

**Comment by Ocramius** [comment] 2016-01-07 04:02
Actually, the [`FloatType`](https://github.com/doctrine/dbal/blob/fbd6ab259240880e3a2bb2dc8e6f0c1a89521cfa/lib/Doctrine/DBAL/Types/FloatType.php) should just work for you :-)

**Comment by trsteel88** [comment] 2016-01-07 04:05
No worries. Yes, I saw FloatType. However, it doesn't let you specify scale/precision. I want to store the data as a decimal with scale/precision but cast it to a float. FloatType is a Double type.

**Comment by Ocramius** [comment] 2016-01-07 04:06
You'll probably need a hybrid type, assuming you can live with the possibility of lossy conversions

**Comment by trsteel88** [comment] 2016-01-07 04:11
Hmm, I could probably even create an EventListener that checks the value before and after by using round() according to the scale set on the mapping for that field.

Thanks for your help.

**Comment by trsteel88** [comment] 2016-01-07 04:14
Or I could just do...

```php
    /**
     * Get price.
     *
     * @return float
     */
    public function getPrice()
    {
        return (float) $this->price;
    }

    /**
     * Set price.
     *
     * @param float $price
     *
     * @return $this
     */
    public function setPrice($price)
    {
        $this->price = sprintf('%.2f', $price);

        return $this;
    }
```

Only downside, if $this->price is used within that model, it isn't going to be a float.

**Comment by Ocramius** [comment] 2016-01-07 04:20
I think it would be best to use an embeddable type (value object) to deal with this sort of issue, so you avoid doing the casts manually every time.

**Comment by inri13666** [comment] 2021-09-18 10:30
```
    public function onFlush(OnFlushEventArgs $eventArgs)
    {
        $em = $eventArgs->getEntityManager();
        $uow = $em->getUnitOfWork();
        $scheduledUpdates = $uow->getScheduledEntityUpdates();
        foreach ($scheduledUpdates as $entity) {
            $entityClass = ClassUtils::getClass($entity);
            $metadata = $em->getClassMetadata($entityClass);

            $changeSet = &$uow->getEntityChangeSet($entity);
            $isChangeSetUpdated = false;

            foreach ($changeSet as $property => $change) {
                if ($metadata->hasField($property)) {
                    $fieldType = $metadata->getTypeOfField($property);
                    if ($fieldType instanceof Type) {
                        $fieldType = $fieldType->getName();
                    }
                } else {
                    $fieldType = Types::STRING;
                }

                if (in_array($fieldType, [Types::DECIMAL])) {
                    $oldValue = null !== $change[0] ? (float) $change[0] : null;
                    $newValue = null !== $change[0] ? (float) $change[0] : null;
                    if ($oldValue === $newValue) {
                        $isChangeSetUpdated = true;
                        unset($changeSet[$property]);
                    }
                }
            }

            if ($isChangeSetUpdated) {
                $uow->recomputeSingleEntityChangeSet($metadata, $entity);
            }
        }
    }
```
