### ISSUE TITLE
getMaxResults() has to be an int, string returned

### ISSUE THREAD

**Issue by mariiok** [doctrine/doctrine2#9087] opened 2021-10-05 10:45 UTC
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.1.0

#### Summary

Query::getMaxResults(): Return value must be of type ?int, string returned in /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php:692 404

#### Previous behavior

No error on ORM version 2.9.6

#### Current behavior

TypeError: Doctrine\ORM\Query::getMaxResults(): Return value must be of type ?int, string returned in /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php:692 404

#### How to reproduce

```
use Doctrine\Common\Collections\Criteria;

        $criteria = new Criteria();
        $criteria->setMaxResults(null);
        $criteria->setFirstResult(null);
        $collection = $this->entity_manager->getRepository($entity_name)->matching($criteria);

        return $collection->count();
```

Looking at: https://github.com/doctrine/collections/blob/1.6.x/lib/Doctrine/Common/Collections/Criteria.php
We can see that $maxResults could be an int or NULL.

```
class Criteria
{
    /** @var int|null */
    private $maxResults;
}

    /**
     * Construct a new Criteria.
     *
     * @param string[]|null $orderings
     * @param int|null      $firstResult
     * @param int|null      $maxResults
     */
    public function __construct(?Expression $expression = null, ?array $orderings = null, $firstResult = null, $maxResults = null)
    {
        $this->expression = $expression;

        $this->setFirstResult($firstResult);
        $this->setMaxResults($maxResults);

        if ($orderings === null) {
            return;
        }

        $this->orderBy($orderings);
    }

    /**
     * Gets maxResults.
     *
     * @return int|null
     */
    public function getMaxResults()
    {
        return $this->maxResults;
    }

    /**
     * Sets maxResults.
     *
     * @param int|null $maxResults The value to set.
     *
     * @return Criteria
     */
    public function setMaxResults($maxResults)
    {
        $this->maxResults = $maxResults;

        return $this;
    }
```

**Comment by derrabus** [comment] 2021-10-05 11:26
Duplicate of #9086

**Closed as completed by derrabus** 2021-10-05 11:26 UTC
