### ISSUE TITLE
Update 1.13.1 Argument #3 ($cascade) must be of type ?array, string given

### ISSUE THREAD

**Issue by lebadapetru** [doctrine/doctrine2#8775] opened 2021-06-19 11:12 UTC
After a `composer update` which updated the doctrine/annotations package to 1.13.1 i received the following error:

```
TypeError {#2023
  #message: "Doctrine\ORM\Mapping\OneToMany::__construct(): Argument doctrine/annotations#3 ($cascade) must be of type ?array, string given, called in /var/www/erp/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 944"
  #code: 0
  #file: "./vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/OneToMany.php"
  #line: 60
  trace: {
    ./vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/OneToMany.php:60 { …}
    ./vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:944 { …}
    ./vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:719 { …}
    ./vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:376 { …}
    ./vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php:178 { …}
    ./vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/PsrCachedReader.php:155 { …}
    ./vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/PsrCachedReader.php:88 { …}
    ./vendor/api-platform/core/src/Util/AnnotationFilterExtractorTrait.php:47 { …}
    ./vendor/api-platform/core/src/Util/AnnotationFilterExtractorTrait.php:112 { …}
    ./vendor/api-platform/core/src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPass.php:65 { …}
    ./vendor/api-platform/core/src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPass.php:52 { …}
    ./vendor/symfony/dependency-injection/Compiler/Compiler.php:91 { …}
    ./vendor/symfony/dependency-injection/ContainerBuilder.php:736 { …}
    ./vendor/symfony/http-kernel/Kernel.php:541 { …}
    ./vendor/symfony/http-kernel/Kernel.php:780 { …}
    ./vendor/symfony/http-kernel/Kernel.php:121 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:168 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:74 { …}
    ./vendor/symfony/console/Application.php:166 { …}
    ./bin/console:43 {
      › $application = new Application($kernel);
      › $application->run($input);
      › 
    }
  }
}

```

**Comment by greg0ire** [comment] 2021-06-19 11:19
The error emanates from a class defined in the ORM. Transferring.

**Comment by greg0ire** [comment] 2021-06-19 11:20
Duplicate of #8720

**Closed as completed by greg0ire** 2021-06-19 11:20 UTC
