### ISSUE TITLE
XSD Validation extention point.

### ISSUE THREAD

**Issue by oleg-andreyev** [doctrine/doctrine2#11349] opened 2024-03-11 21:19 UTC
### Feature Request

In scope of https://github.com/doctrine/orm/pull/6728 XSD validation was added which is awesome but it introduced an issue with popular repo https://github.com/doctrine-extensions/DoctrineExtensions it adds extra XSD elements.

Problem: ORM validates XML against only own XSD and there is no way (except extend or decorate) to add extra XSD like Gedmo.

```
Doctrine\ORM\Mapping\MappingException : libxml error: Element '{http://gediminasm.org/schemas/orm/doctrine-extensions-mapping}versioned': No matching global element declaration available, but demanded by the strict wildcard.
```

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

1. Allow to override XSD location.
2. New XSD should include "ORM" XSD as mandatory (could be validated)
```
<?xml version="1.0" encoding="UTF-8"?>
<schema elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema">
    <import namespace="http://doctrine-project.org/schemas/orm/doctrine-mapping" schemaLocation="./vendor/doctrine/orm/doctrine-mapping.xsd"/>
    <import namespace="http://gediminasm.org/schemas/orm/doctrine-extensions-mapping" schemaLocation="./schemas/orm/doctrine-extensions-mapping-3-0.xsd"/>
</schema>

```

**Comment by oleg-andreyev** [comment] 2024-03-11 21:20
Current "workaround":

```
<?php

namespace Gedmo\Mapping\Driver\ORM;

use Doctrine\ORM\Mapping\Driver\XmlDriver as BaseXmlDriver;
use Doctrine\ORM\Mapping\MappingException;
use Doctrine\Persistence\Mapping\Driver\FileLocator;
use DOMDocument;

class XmlDriver extends BaseXmlDriver
{
    public function __construct(
        string|array|FileLocator $locator,
        string $fileExtension = self::DEFAULT_FILE_EXTENSION,
        private readonly bool $isXsdValidationEnabled = true,
    )
    {
        parent::__construct($locator, $fileExtension, $isXsdValidationEnabled);
    }

    protected function loadMappingFile($file)
    {
        $this->validateMapping($file);

        $result = [];
        // Note: we do not use `simplexml_load_file()` because of https://bugs.php.net/bug.php?id=62577
        $xmlElement = simplexml_load_string(file_get_contents($file));
        assert($xmlElement !== false);

        if (isset($xmlElement->entity)) {
            foreach ($xmlElement->entity as $entityElement) {
                /** @psalm-var class-string $entityName */
                $entityName          = (string) $entityElement['name'];
                $result[$entityName] = $entityElement;
            }
        } elseif (isset($xmlElement->{'mapped-superclass'})) {
            foreach ($xmlElement->{'mapped-superclass'} as $mappedSuperClass) {
                /** @psalm-var class-string $className */
                $className          = (string) $mappedSuperClass['name'];
                $result[$className] = $mappedSuperClass;
            }
        } elseif (isset($xmlElement->embeddable)) {
            foreach ($xmlElement->embeddable as $embeddableElement) {
                /** @psalm-var class-string $embeddableName */
                $embeddableName          = (string) $embeddableElement['name'];
                $result[$embeddableName] = $embeddableElement;
            }
        }

        return $result;
    }

    private function validateMapping(string $file): void
    {
        if (! $this->isXsdValidationEnabled) {
            return;
        }

        $backedUpErrorSetting = libxml_use_internal_errors(true);

        try {
            $document = new DOMDocument();
            $document->load($file);

            if (! $document->schemaValidate(__DIR__ . '/../../../../doctrine-mapping.xsd')) {
                throw MappingException::fromLibXmlErrors(libxml_get_errors());
            }
        } finally {
            libxml_clear_errors();
            libxml_use_internal_errors($backedUpErrorSetting);
        }
    }
}
```

**Comment by greg0ire** [comment] 2024-03-11 22:03
Duplicate of #11123

Feel free to add any comments on that issue.

**Closed as not planned by greg0ire** 2024-03-11 22:03 UTC
