### ISSUE TITLE
@OrderBy annotation does not apply

### ISSUE THREAD

**Issue by tszymanek** [doctrine/doctrine2#5539] opened 2015-12-09 13:27 UTC
As stated in my [stackoverflow question](http://stackoverflow.com/questions/34122195/sort-arraycollection-with-orderby-annotation-issue) there appears to be a bug causing the ArrayCollection to be unsorted when I'm retrieving the entity with `find(1)`. The whole thing miraculously works when I use `findOneBy(array('id' => 1))`. Please check the link mentioned above for further detail. 

Hope I wrote this in the right section and it's going to be resolved. Best regards

**Comment by dlancea** [comment] 2016-05-19 17:53
This might be related to Issues #4256 and #4739 .

Try removing `fetch="EAGER"`

**Comment by guilhermeblanco** [comment] 2016-05-19 18:07
Closing as a duplicate of #4256

**Closed by guilhermeblanco** 2016-05-19 18:07 UTC
Labels: Bug
