### ISSUE TITLE
Missing auto_increment if custom repository annotation presented

### ISSUE THREAD

**Issue by olegsv** [doctrine/doctrine2#6148] opened 2016-11-24 22:02 UTC
An entity class contains repository annotation, and two fields with GeneratedValue annotations, one defined as "AUTO" and another one as "GUID" . 

A table corresponding to the entity is present in DB.

```
CREATE TABLE `my_entity` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `ident` varchar(16) DEFAULT NULL COMMENT 'GUID',
   ...
```

Running ` doctrine:schema:update ` in Symfony 2.8 / Doctrine 2.4.8 produces incorrect SQL in the following cases:

1. if Repository and two GeneratedValue annotations are present, the following SQL is generated. Note the missing AUTO_INCREMENT

`ALTER TABLE my_entity CHANGE id id BIGINT UNSIGNED NOT NULL;`

2. when Repository and only one GeneratedValue annotation for the primary key  present, the resulting SQL is correct but does exactly nothing.

`ALTER TABLE my_entity CHANGE id id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL;`

3. When Repository annotation is not present, and both fields have GeneratedValue annotation -  no SQL is generated , which is a desired behaviour.

```
/** MyEntity
 *
 * @ORM\Table(name="my_entity")
 * @ORM\Entity(repositoryClass="My\MyBundle\Repository\MyRepository123")
 */
class MyEntity
{
    /**
     * @var int
     *
     * @ORM\Column(nullable=false, type="bigint",options={"unsigned":true,"auto_increment":true} )
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    /**
     * @var string
     *
     * @ORM\Column(name="ident", type="string", length=16, nullable=true, options={"comment":"GUID"} )
     * @ORM\GeneratedValue(strategy="UUID")
     */
    private $ident;
    ....
```

**Comment by Ocramius** [comment] 2016-11-25 15:13
The ORM only supports single-column generated values. We probably need to throw an exception in the mapping load process.

**Comment by olegsv** [comment] 2016-11-25 21:04
In case 2 the mapper incorrectly produces similar SQL, there should be no SQL generated.

**Comment by voronkovich** [comment] 2016-11-30 14:27
@olegsv, your example is not correct. You missed an `@Id` annotation in the `ident` property. The `@GeneratedValue` doesn't work without the `@Id`. See http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/annotations-reference.html#generatedvalue

**Comment by olegsv** [comment] 2016-11-30 14:33
@voronkovich see p.2 for bug that occurs without second generated value

**Comment by ostrolucky** [comment] 2018-08-06 22:31
I gave this a go and I can't reproduce. Also, support for DB-generated UUIDs has been dropped in Doctrine/DBAL 3.0. See https://github.com/doctrine/doctrine2/pull/7330 or https://github.com/doctrine/dbal/pull/3211. Since it's very likely this issue is no longer relevant, I'm going to close this issue. If I am wrong and it's still relevant, please don't hesitate to comment here with reproducer based on master branch and we will reopen.

**Closed by ostrolucky** 2018-08-06 22:31 UTC
Labels: Bug
