### ISSUE TITLE
Query with OneToOne JOIN returns single result?

### ISSUE THREAD

**Issue by dVVIIb** [doctrine/doctrine2#8570] opened 2021-03-27 11:23 UTC
I have a query of the form:

$query = $entityManager->createQuery('SELECT a.id FROM App\Entities\EntityA a JOIN a.entityStatus s');

When the mapping is of the form:

@ORM\OneToOne(targetEntity="App\Entities\EntityStatus", mappedBy="entityA")

I get a single result.

However, when the association is OneToMany, I get multiple results for the same data. The only alteration being @ORM\OneToOne -> @ORM\OneToMany

The data seem to be ok, and map on-to-one to distinct ids.

Am I missing something?

I expect a distinct row per each on-to-one mapping.

"doctrine/doctrine-bundle": "^2.2", "doctrine/doctrine-migrations-bundle": "^3.0", "doctrine/orm": "^2.8"

@greg0ire, Your answer doesn't make any sense. I did post this here because I think this is a bug. I don't understand why you closed my issue without allowing me to respond. StackOverflow is no place for bug reports. And I tried as you suggested and selected a but this did not help. With the JOIN, I still get a single result. Note, that I don't wish to select a. The association IS identified/enforced by the id. Note that the query I provided is a simplified version reduced to demo the issue. The original query had more fields. If this IS a bug, then this issue should remain open. Otherwise, kindly explain why this is not a bug, and how this issue should be addressed...

Thank you.

**Comment by greg0ire** [comment] 2021-03-27 12:48
You can still respond on #8568  if you wish to closing, does not mean locking the conversation.

**Closed as completed by greg0ire** 2021-03-27 12:48 UTC

**Comment by greg0ire** [comment] 2021-03-27 12:50
Duplicate of #8568
