### ISSUE TITLE
Allow doctrine/common 2.7

### ISSUE THREAD

**Issue by garak** [doctrine/doctrine2#6157] opened 2016-12-02 12:55 UTC
Is there a reason for requirements like these ones?
```
        "doctrine/dbal": ">=2.5-dev,<2.7-dev",
        "doctrine/common": ">=2.5-dev,<2.7-dev",
```
Can't you just require something like these?
```
        "doctrine/dbal": "^2.5",
        "doctrine/common": "^2.5",
```

Current requirements prevent `doctrine/common:2.7.0` (and above)

**Comment by Ocramius** [comment] 2016-12-02 18:11
We had multiple internal annoying BC breaks over the years (not exposed in the API), so we're always going with baby-steps here. Closing as duplicate of #6156

**Closed by Ocramius** 2016-12-02 18:11 UTC
