### ISSUE TITLE
Duplicate definition of column 'id' on entity '<FQCN>' in a field or discriminator column mapping.

### ISSUE THREAD

**Issue by Arkemlar** [doctrine/doctrine2#11136] opened 2023-12-22 20:45 UTC
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.16.*

#### Summary

I use inheritance mapping and since v2.16 it is no longer working. Exact scheme example in the bottom.

#### Previous behavior

Worked fine.

#### Current behavior

In a newer version I got following error:
`Duplicate definition of column 'id' on entity 'App\Context\Task\Model\TaskHistory' in a field or discriminator column mapping.`

#### How to reproduce

```php
abstract class Entity
{
    #[
        ORM\Id,
        ORM\GeneratedValue,
        ORM\Column(type: 'bigint', nullable: false, options: ['unsigned' => true])
    ]
    protected int $id;
}

#[
    ORM\Entity,
    ORM\InheritanceType('JOINED'),
    ORM\DiscriminatorMap([
        'task' => TaskHistory::class,
    ])
]
abstract class History extends Entity
{}


#[ORM\Entity]
class TaskHistory extends History
{}
```
Then `bin/console doctrine:schema:validate`if you use symfony.

If I move `id` field to `History` class, then it works as expected. Also works if I use trait for Id instead of abstract class.

I know that doctrine not guarantees plain old OOP classes inheritance to work but since it is BC break I decided to report it because it might indicate a new mapping bug.

**Comment by mpdude** [comment] 2023-12-22 21:22
So the `Entity` class is intentionally not marked as an entity, and you know that this is out of supported configuration?

**Comment by mpdude** [comment] 2023-12-22 21:47
Might be a duplicate of #11129

**Comment by Arkemlar** [comment] 2024-01-03 20:24
> So the `Entity` class is intentionally not marked as an entity, and you know that this is out of supported configuration?

Exactly! And I accent that I made this Issue not because it _SHOULD_ work (it shouldn't), but because it is BC break.

**Comment by mpdude** [comment] 2024-01-03 23:46
No, it’s not. It is unsupported, unspecified behavior and as such not subject to any promises given.

**Closed as not planned** 2024-01-03 23:46 UTC
