### ISSUE TITLE
Could not convert PHP value of type 'DateTimeImmutable' to type 'datetime'

### ISSUE THREAD

**Issue by bazo** [doctrine/doctrine2#5637] opened 2016-01-28 13:00 UTC
hi,

i've been using DateTimeImmutable for some time now as parameters to query builder queries, dql queries and also in entity values

in one project there's a code more than a year old that uses DateTimeImmutable and it worked all the time.

but after some update of doctrine in the past few days this error started popping up

Could not convert PHP value of type 'DateTimeImmutable' to type 'datetime'. Expected one of the following types: null, DateTime

i remember this was in issue when php 5.5 was new, so this seems like regression to me

**Comment by bazo** [comment] 2016-01-28 13:30
stable 2.5.4 does not have this bug

**Comment by Jean85** [comment] 2016-02-08 17:20
Which version where you using when reproducing the bug?

**Comment by Ocramius** [comment] 2016-02-08 20:07
Since it doesn't concern the current stable version, closing as `invalid`

**Comment by teohhanhui** [comment] 2016-06-23 09:07
@Ocramius You forgot to close this... :smile:

**Comment by Ocramius** [comment] 2016-07-05 16:45
@teohhanhui don't drink and review! 🍻  Thanks for the ping :)

**Closed by Ocramius** 2016-07-05 16:45 UTC
Labels: Bug, Invalid
