### ISSUE TITLE
CLI output to stdout instead of error

### ISSUE THREAD

**Issue by remco-pc** [doctrine/doctrine2#10555] opened 2023-03-02 00:05 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 

```
doctrine/annotations               1.14.3          Docblock Annotations Parser
doctrine/cache                     2.2.0           PHP Doctrine Cache library is a popular cache implementation tha...
doctrine/collections               1.8.0           PHP Doctrine Collections library that adds additional functional...
doctrine/common                    3.4.3           PHP Doctrine Common project is a library that provides additiona...
doctrine/dbal                      3.6.0           Powerful PHP database abstraction layer (DBAL) with many feature...
doctrine/deprecations              v1.0.0          A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-...
doctrine/doctrine-bundle           2.8.3           Symfony DoctrineBundle
doctrine/event-manager             1.2.0           The Doctrine Event Manager is a simple PHP event system that was...
doctrine/inflector                 2.0.6           PHP Doctrine Inflector is a small library that can perform strin...
doctrine/instantiator              1.5.0           A small, lightweight utility to instantiate objects in PHP witho...
doctrine/lexer                     2.1.0           PHP Doctrine Lexer parser library that can be used in Top-Down, ...
doctrine/orm                       2.14.1          Object-Relational-Mapper for PHP
doctrine/persistence               2.5.7           The Doctrine Persistence project is a set of shared interfaces a...
doctrine/sql-formatter             1.1.3           a PHP SQL highlighting library
```

#### Summary

if i run a doctrine command in the console, it writes to the error pipe instead of stdOut.
I also see this with composer, why is this ?

Why aren't you writing to stdOut with: 

 Processing entity "Entity\UserLogger"
 Processing entity "Entity\User"
 Processing entity "Entity\Profile"
 Processing entity "Entity\Application"
 Processing entity "Entity\MailQueue"
 Processing entity "Entity\Role"
 Processing entity "Entity\Extension"
 Processing entity "Entity\Permission"
 Processing entity "Entity\Parameter"

#### Current behavior

writing to error pipe.

#### How to reproduce

r3m doctrine orm:generate-proxies

it runs doctrine orm:generate-proxies but changes the owner of the files to www-data if running root.

#### Expected behavior

writing to stdOut with this information so it won't trigger error events but normal events.

**Comment by greg0ire** [comment] 2023-03-02 11:39
Stderr is badly named, it's meant for notifications to humans, while stdout is the output of your program, ready to be piped into another program, unpolluted with diagnosis messages.

**Comment by greg0ire** [comment] 2023-03-02 11:49
Relevant : https://github.com/git/git/commit/e258eb4800e30da2adbdb2df8d8d8c19d9b443e4

**Comment by remco-pc** [comment] 2023-03-02 18:48
so i need a registry which handles stderr as messages instead of errors, i cannot perform actions on stdErr as i should / could with only error messages (send an email event), in my framework i pipe everything usefull to stdout and exceptions to stdErr so i can add an event there, in your case i cannot attach an event or i need an explicit error message in the output which i can capture somehow  with stristr for example? or are the exceptions in the stdErr ? pipe (2), sure i can save the output and if it changes send an email,

**Comment by greg0ire** [comment] 2023-03-02 22:29
Indeed you can't, same for git and composer. We never committed to supporting this use case you are describing as far as I know. On the other hand, we do have a few tests in at least one Doctrine project where we check that stdout consists in valid Sql statements and is not polluted by success messages that go to stderr. Let's close since this is not a bug.

**Closed as completed by greg0ire** 2023-03-02 22:29 UTC
Labels: Question

**Comment by remco-pc** [comment] 2023-03-04 23:46
i've ended up for my system update with now 2 notification states for system.update.notification:

```json
{
    "notification": [
        {
            "action": "system.update.notification",
            "filter": [
                {
                    "require": [
                        "93d82768-7493-4333-94c8-95a7f8046160"
                    ],
                    "action": "pass"
                },
                {
                    "where": {
                        "key": "type",
                        "type": [
                            "hexadecimal",
                            "integer",
                            "float"
                        ],
                        "operator": "in.array"
                    },
                    "require": [
                        "15e8ffb2-1d59-431d-8e1e-4ead23403fad"
                    ],
                    "action": "pass"
                }
            ]
        }
    ]
}
```

```json
{
    "require": [
        "Everything up-to-date",
        ""
    ]
}
````

```json
{
  "require" : [
    "To [redacted].git",
    "   5e31c009..2a33b84b  master -> master",
    ""
  ]
}
```

**Comment by remco-pc** [comment] 2023-03-07 22:15
if made a little change to above statement:
```json
{
    "stream": {
        "input": [],
        "output": [],
        "notification": [
            {
                "action": "system.update.notification",
                "create": {
                    "filter": [
                        {
                            "document": [
                                "bffd6dd6-3998-470d-a89c-bcf037d868d9"
                            ],
                            "where": [
                                {
                                    "operator": "!==",
                                    "token": "token"
                                }
                            ]
                        },
                        {
                            "document": [
                                "5ebcdbff-6342-446b-a102-34c454a8238e"
                            ],
                            "where": [
                                {
                                    "operator": "!==",
                                    "token": "token"
                                },
                                {
                                    "key": "type",
                                    "type": [
                                        "hexadecimal",
                                        "integer",
                                        "float"
                                    ],
                                    "operator": "!in.array"
                                }
                            ]
                        }
                    ]
                }
            }
        ]
    }
}
```

where document is the output of stdErr
the create filter works as such, when no tokens are left no save is performed and no email is send, if it encounters a new message it will save it and send an email but in this case: (git commit message) has some hexadecimal / integer values which are different each time.
