### ISSUE TITLE
Single id is not allowed on composite primary key in entity

### ISSUE THREAD

**Issue by podorozhny** [doctrine/doctrine2#6333] opened 2017-03-13 08:32 UTC
I have same issue as described in this [question](http://stackoverflow.com/questions/39099801/symfony-3-doctrine-composite-key-single-id-is-not-allowed-on-composite-primary).

Can't use composite keys in entity, while having one of them being auto-generated.

For example:
```
/**
 * @Entity
 */
class User
{
    /**
      * @Id
      * @Column(type="integer")
      */
    private $foo;

    /**
      * @Id
      * @Column(type="integer")
      */
    private $bar;
}
``` 

This will work until I add @GeneratedValue() on one of them.

Thanks.

**Comment by Ocramius** [comment] 2017-03-13 08:36
Multi-column composite identifiers are not supported, and are going to stay like that for a while, since we didn't figure out how to properly handle them. A custom identifier generator strategy would be preferrable on your side.

Closing as `won't fix`

**Closed by Ocramius** 2017-03-13 08:36 UTC

**Comment by adrienbrault** [comment] 2018-01-25 20:33
@Ocramius Could you explain what the issue/limitation is ?

**Comment by Ocramius** [comment] 2018-01-25 20:36
The problem is that the `UnitOfWork` and many other internal components assume that an identifier is either generated or not: we don't have a concept in between. I know @guilhermeblanco did some work on this for 3.x, but I don't know how far he got.

**Comment by marquez20** [comment] 2020-04-04 16:42
You need to remove all @Id in properties description except protected $id.

**Comment by iamkhusainov7** [comment] 2023-09-24 11:37
> Multi-column composite identifiers are not supported, and are going to stay like that for a while, since we didn't figure out how to properly handle them. A custom identifier generator strategy would be preferrable on your side.
> 
> Closing as `won't fix`

There is a disadvantage of it. Like, JoinColumn referencedColumn key must always reference the entity identifier. For instance, I cannot use uuid as a foreign key if uuid is not the primary key.
