### ISSUE TITLE
Identity map error when running SELECT on the same table alias more than once

### ISSUE THREAD

**Issue by emhovis** [doctrine/doctrine2#10889] opened 2023-08-08 15:51 UTC
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.16.0

#### Summary

Upon upgrading to 2.16, the fetch queries for the entity "Foo" started throwing the following: 
```
(Bar@13041) has no identity/no id values set. It cannot be added to the identity map. 
```
I went absolutely crazy searching for the issue. Note, Bar is a 3rd degree association to Foo-there are 2 entities between Foo and Bar! 

After much digging, I found that the problem comes from the many joins we have on Foo and its associated entities. There are *many* joins on Foo and when all of the aliases were first written, one of the aliases was entered twice when passed into the array for select. Removing this duplicate join-table alias from the array passed into select resolved the issue.

I'm not 100% certain that the new behavior is a "bug" per-se, but it seems like it breaking change that should be noted.

#### Previous behavior

Querying the DB with multiple of the same table alias selected would return results without error.

#### Current behavior

Querying the DB returns with multiple of the same selected table alias causes an identity mapping error.

#### How to reproduce

Add joins to an entity, call a select statement with an argument of an array that includes the same join alias twice, e.g. 
```
$qb->leftJoin("{$a}.foo", "joinFoo")
      ->leftJoin("{$a}.bar", 'joinBar');
$qb->select([
            self::TABLE_ALIAS,
            'joinFoo',
            'joinBar',
            'joinFoo'
]);
```

**Comment by mpdude** [comment] 2023-08-09 16:42
Do you think you could provide a (failing) test that reproduces the issue, ideally as a PR?

Have a look at the `GHxxxTest.php` functional test cases in this repo, that should help you get going. You can define entities in the test files as well, and there are also some entity “models” that you might want to use.

**Comment by mpdude** [comment] 2023-08-09 16:47
That duplicate alias, has it been reused for different tables? Or for the same table but in multiple stages of a join hierarchy?

Or was it just given multiple times in the DQL `SELECT` clause?

**Comment by emhovis** [comment] 2023-08-09 18:11
> That duplicate alias, has it been reused for different tables? Or for the same table but in multiple stages of a join hierarchy?
> 
> Or was it just given multiple times in the DQL `SELECT` clause?

In my case, It was passed in multiple times in a singular DQL SELECT clause. 
I just tested adding one again in a separate addSelect clause and adding a select to a table that was previously defined also throws the issue.

The following throws the error:
```
$qb->select([
            self::TABLE_ALIAS,
            'joinA',
            'joinB',
            'joinC',
            'joinB'
]);
```
This will also throw the error:
```
$qb->select([
            self::TABLE_ALIAS,
            'joinA',
            'joinB',
            'joinC',
]);
$qb->addSelect('joinC');
```
Prior to 2.16.0, the above 2 don't cause any issue. I don't necessarily think the old behavior is necessarily ideal though. I don't personally see any valid reason using select on the same alias twice- even if you try to modularize joins+selects, an error gets thrown if you try to create an already-existing table alias. The only way I can think of someone running into this issue is via typo or an entry mistakenly being added twice. In my case, someone wrote a fed a select a ~20 value array with similarly-named aliases and a single one of those was mistakenly added twice.

My biggest gripe is that if upgrading to 2.16 breaks existing code then it should at least be noted in the changelog, changed to a deprecation warning instead of error and or pushed to 3.0. Also note, the error given doesn't exactly help pinpoint the issue... fixing that may alleviate some woes.

**Comment by emhovis** [comment] 2023-08-09 18:19
> Do you think you could provide a (failing) test that reproduces the issue, ideally as a PR?
> 
> Have a look at the `GHxxxTest.php` functional test cases in this repo, that should help you get going. You can define entities in the test files as well, and there are also some entity “models” that you might want to use.

I'll see what I can do!

**Comment by mpdude** [comment] 2023-08-09 18:53
I’d assume this was not an intentional change, but a side effect of something else and not covered/caught by tests.

**Comment by mpdude** [comment] 2023-08-09 19:05
I've created #10901, but that's not yet sufficient to show the issue.

Feel free to open a PR against https://github.com/mpdude/doctrine2/tree/repro-10889 if you have any idea what needs to be included.

**Comment by emhovis** [comment] 2023-08-09 21:35
Now I'm intrigued...  I can't seem to replicate the issue in the doctrine test suite. I'll have to port over some more associations, filters etc and dig a bit deeper to see what the real problem is.

**Comment by emhovis** [comment] 2023-08-09 22:19
Still haven't managed to replicate it in a functional test but found something intriguing.

This doesn't throw the error:
```
        $a = self::TABLE_ALIAS;
        $qb = $this->createQueryBuilder($a)->select();
        $qb->leftJoin("{$a}.entityB", "joinB")
            ->leftJoin("joinB.entityC", "joinC");
        $qb->select([
            $a,
            'joinB',
            'joinB',
            'joinC',
            'joinC',
        ]);
 ```
But this does:
```
        $a = self::TABLE_ALIAS;
        $qb = $this->createQueryBuilder($a)->select();
        $qb->leftJoin("{$a}.entityB", "joinB")
            ->leftJoin("joinB.entityC", "joinC");
        $qb->select([
            $a,
            'joinB',
            'joinC',
            'joinC',
        ]);
 ```

**Comment by mpdude** [comment] 2023-08-15 13:19
X-Ref https://github.com/sulu/sulu/issues/7138

**Comment by mpdude** [comment] 2023-08-23 20:33
Anyone been able to reproduce?

**Comment by noemi-salaun** [comment] 2023-08-24 15:32
I managed to replicate the problem with a minimum of code with doctrine/orm 2.16.1

Create this entities
```php
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity, ORM\Table(name: 'user')]
class User
{
    #[ORM\Id, ORM\Column]
    private int $id;
}

#[ORM\Entity, ORM\Table(name: 'finger')]
class Finger
{
    #[ORM\Id, ORM\Column]
    private int $id;
}

#[ORM\Entity, ORM\Table(name: 'hand')]
class Hand
{
    #[ORM\OneToOne, ORM\Id]
    private User $user;

    #[ORM\ManyToOne]
    private ?Finger $thumb;
}
```

Create the MySQL database
```sql
create table finger
(
    id int not null primary key
);

create table user
(
    id int not null primary key
);

create table hand
(
    userId  int not null primary key,
    thumbId int null
);

INSERT INTO user (id) VALUES (1);
INSERT INTO hand (userId, thumbId) VALUES (1, null);
```

And then execute this query
```php
        $entityManager
            ->getRepository(Hand::class)
            ->createQueryBuilder('hand')
            ->leftJoin('hand.thumb', 'thumb')->addSelect('thumb')
            ->getQuery()
            ->getResult();
```

It should produce this error
> The given entity of type 'Finger' (Finger@471) has no identity/no id values set. It cannot be added to the identity map.

If you create a finger and set a finger NOT NULL in the hand, no error
If you join but not addSelect in the query, no error
If the Hand use a simple int as ID instead of a relation, no error
If you rollback doctrine/orm to v2.15, no error

I hope it will help you identify the issue

**Comment by mpdude** [comment] 2023-08-24 16:44
So this is related to having an object and/or association value serve as the ID?

I have seen this pattern quite a few times in recent bug reports, maybe that deserves a more thoughtful examination.

**Comment by mpdude** [comment] 2023-08-24 21:07
#10788, #10852

**Comment by noemi-salaun** [comment] 2024-01-16 09:38
Any news on this issue ? The v2.17  is released but I'm still locked on v2.15 because of this :/
The issue is still present on v2.17

**Comment by noemi-salaun** [comment] 2024-01-27 14:37
By going threw each commits between 2.15.5 and 2.16.0 I found that the issue appeared after this commit https://github.com/doctrine/orm/commit/01a14327d2404885897961851659b467ec966d74 

I'll continue digging

**Comment by noemi-salaun** [comment] 2024-01-28 17:53
Here https://github.com/doctrine/orm/pull/11194 is my PR which seems to fix the issue, at least for my case

**Comment by alexander-schranz** [comment] 2024-06-27 16:27
Think this can be closed as fixed in https://github.com/doctrine/orm/pull/11194 ?

**Closed as completed** 2024-06-27 17:41 UTC
