### ISSUE TITLE
Proxy generator messed with PHP7 void return type hint

### ISSUE THREAD

**Issue by vpArth** [doctrine/doctrine2#6163] opened 2016-12-06 18:16 UTC
Proxy generator generate followed code:  

```php
public function setStatus(string $status) : void
{
  $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);
  return parent::setStatus($status);
}
```

`return` statement should be omitted if `void` return typehint presented.

It should be just `parent::setStatus($status);` without `return`
___
workaround is not to use `void` return typehint

**Comment by lcobucci** [comment] 2016-12-06 18:17
Which version of doctrine/common are you using? This was fixed on 2.7.x

**Comment by Ocramius** [comment] 2016-12-06 18:18
@vpArth `void` is currently only supported if you run with `doctrine/common` `2.7.*`. Upgrading the dependency here will be done soon.

**Comment by vpArth** [comment] 2016-12-06 18:24
Glad to hear that.
I'm unhappily using doctrine as a part of symfony3.2, which uses `doctrine/orm@v2.5.5`/`doctrine/common@<2.7-dev`

**Comment by Ocramius** [comment] 2016-12-06 18:24
Closing as duplicate of #6156

**Closed by Ocramius** 2016-12-06 18:24 UTC
