### ISSUE TITLE
The TopologicalSort reverts the order of persisted entities

### ISSUE THREAD

**Issue by netbull** [doctrine/doctrine2#11057] opened 2023-11-11 15:12 UTC
### Bug Report

This was reported by #10897 and #10864, but the order is reversed when the nodes are also edges.

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.16.0

#### Summary

Use case:
Entity Booking and Entity Guest.
If we persist 3 Guests to existing Booking then we have the correct order of the guests as [here](https://github.com/doctrine/orm/blob/2.16.x/lib/Doctrine/ORM/Internal/TopologicalSort.php#L107C23-L107C23) its used `array_reverse` because [here](https://github.com/doctrine/orm/blob/2.16.x/lib/Doctrine/ORM/Internal/TopologicalSort.php#L163) `array_unshift` is used.

#### Current behavior

if we persist new Booking with the same collection of Guests the collection is reversed, because the Guest nodes are also edges to Entity Booking.

#### How to reproduce

Persist 3 Guest Entities A, B and C and the order will be kept.
Persist new Booking Entity with 3 Guest Entities and the order of the guests will be C, B and A

#### Expected behavior

The edges array should be also reversed while iterating, the same way as the nodes.

**Comment by derrabus** [comment] 2023-11-11 15:36
We don't guarantee any order in which entities are being persited. Please elaborate why you believe the current behavior to be defective.

**Comment by netbull** [comment] 2023-11-11 15:42
@derrabus [this](https://github.com/doctrine/orm/blob/2.16.x/lib/Doctrine/ORM/Internal/TopologicalSort.php#L103C1-L104C1) says it all basically.

If we try to keep the order the same when the entities are added as nodes, then we should try keeping the order also if they are also edges.

**Comment by mpdude** [comment] 2023-11-12 11:46
#11058 has more elaborate discussion on the potential requirements or expectations

**Comment by derrabus** [comment] 2023-11-14 12:11
Let's close this issue then. The behavior described here is not a bug.

We can continue to discuss on #11058 whether we want to change the current behavior or not.

**Closed as not planned by derrabus** 2023-11-14 12:11 UTC
Labels: Bug
