### ISSUE TITLE
'resolveMagicCall()' classify wrong? snake_case fields cannot be found

### ISSUE THREAD

**Issue by nsd4npo** [doctrine/doctrine2#10939] opened 2023-09-08 11:54 UTC
### Discussed in https://github.com/doctrine/orm/discussions/10938

<div type='discussions-op-text'>

<sup>Originally posted by **nsd4npo** September  8, 2023</sup>
Greetings,

I'm using a custom function within my `defaultRepository` extender class called `findOneOrCreateByField($fieldName, $fieldValue)`. Here's a snippet of how it works:
```
$inflector = InflectorFactory::create()->build();
$field = $inflector->classify($field);
$finder = "findOneBy" . $field;
$entity = $this->$finder($fieldValue);
```

However, I encountered an issue when using it with the parameters `testTime` and `\DateTime("now")`, which resulted in a "field not found" error. After some debugging, I discovered the source of the problem in this (shortened) code block:

```
private function resolveMagicCall(string $method, string $by, array $arguments)
    $fieldName = lcfirst(self::$inflector->classify($by));

    if (!($this->_class->hasField($fieldName) || $this->_class->hasAssociation($fieldName))) {
        throw InvalidMagicMethodCall::becauseFieldNotFoundIn(
```
https://github.com/doctrine/orm/blob/2.16.x/lib/Doctrine/ORM/EntityRepository.php#L358-L360

In this context, the code uses classify on the field name, resulting in `TestTime`. The subsequent `hasField` check fails because it's looking for a `test_time` field instead of `TestTime`.

![grafik](https://github.com/doctrine/orm/assets/143995254/b5dbd732-26a3-41a2-afd1-391fda907eda)

My conclusion is that for the `hasField` check, it should use snake_case or tableize, while for the `hasAssociation` check, using classify is appropriate.

Workaround in findOneOrCreateByField:
```
$field = $inflector->tableize($field);
$entity = $this->findOneBy([$field => $fieldValue]);
```

**Comment by derrabus** [comment] 2023-09-11 11:26
We don't need two threads for the same topic. Duplicate of #10938

**Closed as not planned by derrabus** 2023-09-11 11:26 UTC
