### ISSUE TITLE
ERROR:  index "primary" does not exist 

### ISSUE THREAD

**Issue by tlorens** [doctrine/doctrine2#6271] opened 2017-02-01 14:37 UTC
Cannot for the life of me find where this `DROP INDEX "primary";` is coming from.  If I execute each query statement generated from the output of "doctrine:schema:update" everything goes just fine.  Symfony 3.2 / Postgres 9.6.1 / Doctrine 2.5 (bundle 1.6)

```[Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'DROP INDEX "primary"':
  SQLSTATE[42704]: Undefined object: 7 ERROR:  index "primary" does not exist
```
I've searched my code and there's not a single instance of declaring any indexes named primary.

**Comment by Ocramius** [comment] 2017-02-01 14:40
This information is not sufficient to provide any help on our side. You'll have to debug further, maybe with a trace and dumping the schema diff object.

Closing as `invalid`

**Closed by Ocramius** 2017-02-01 14:40 UTC

**Comment by tlorens** [comment] 2017-02-10 03:07
Dug a little deeper into the issue.  I may actually attempt to fix it.  Seems like any time a primary key is changed (standard sequence, auto-increment to/from guid) it has an issue fetching the tables metadata (primary keys/index name).  I'm going take a stab at this on my own and see if I can come up with the fix

**Comment by johnpancoast** [comment] 2017-03-11 19:10
@Ocramius this is definitely a legit bug. It has seemed intermittent for me but I can reproduce it using postgres and a composite key.

* Add the following entity and create your schema.
```php
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class Test
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id()
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id()
     */
    protected $test;
}
```

* Then just remove the second index and run an update.

**Comment by Ocramius** [comment] 2017-03-11 19:12
@johnpancoast can you put this in a test case? I think this might be a DBAL issue though.

**Comment by johnpancoast** [comment] 2017-03-11 19:12
@Ocramius sure.

**Comment by plimpton** [comment] 2017-05-16 18:50
Just came across this as well, postgresql trying to remove a composite key and replace it with a single id column because i needed to add a WHERE conditional to the composite key

**Comment by Ocramius** [comment] 2017-05-20 13:28
@plimpton try making a test case and a new PR with just the failing scenario, if you can

**Comment by jrysig** [comment] 2017-06-15 16:59
I can reproduce this problem too.


```php
<?php
// bootstrap.php
require_once "vendor/autoload.php";

use Doctrine\ORM\Tools\Setup;
use Doctrine\ORM\EntityManager;

$isDevMode = true;

$paths = array(__DIR__.'/entity');
$config = Setup::createAnnotationMetadataConfiguration($paths, $isDevMode, null, null, false);

$dbParams = array(
    'driver'   => 'pdo_pgsql',
    'user'     => 'doctrine_test',
    'password' => 'doctrine_test',
    'dbname'   => 'doctrine_test',
    'host'     => 'localhost',
    'charset'  => 'UTF8',
);

$entityManager = EntityManager::create($dbParams, $config);
```

```php
<?php
// cli-config.php
use Doctrine\ORM\Tools\Console\ConsoleRunner;

require_once 'bootstrap.php';

return ConsoleRunner::createHelperSet($entityManager);
```

```php
<?php
// entity/user.php
namespace Entity;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class User
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     */
   private $sapid;
}
```

```json
# composer.json
{
    "name": "john/doctrine_test",
    "require": {
        "doctrine/orm": "*"
    }
}
```

(create postgresql user and database, see dbParams)

`composer install`
`vendor/bin/doctrine orm:schema-tool:update --force`
> Updating database schema...
> Database schema updated successfully! "2" queries were executed

(rename primary key sapid to something else)
`vendor/bin/doctrine orm:schema-tool:update --force`
> Updating database schema...
> [Doctrine\DBAL\Exception\DriverException]                                    
> An exception occurred while executing 'DROP INDEX "primary"':                
> SQLSTATE[42704]: Undefined object: 7 ERROR:  index "primary" does not exist  

`vendor/bin/doctrine orm:schema-tool:update --dump-sql`
> DROP INDEX "primary";
> ALTER TABLE "User" RENAME COLUMN sapid TO sapid2;
> ALTER TABLE "User" ADD PRIMARY KEY (sapid2);

**Comment by anacicconi** [comment] 2017-06-22 14:35
I have the same bug using Doctrine + Oracle when I'm changing a composite key.

**Comment by jrysig** [comment] 2017-06-22 20:52
@Ocramius, could you please re-open this issue?

**Comment by Ocramius** [comment] 2017-06-23 01:20
As asked already twice, a test case is needed. The above are examples.

**Comment by johnpancoast** [comment] 2017-06-23 02:06
Apologies for not getting to writing this test case, but I have no time at the moment due to other projects (typical story, I know). It's easily re-produceable using those steps iirc. That's the most I can offer at the moment, unfortunately.

**Comment by simPod** [comment] 2017-12-27 17:43
I think this is being resolved in https://github.com/doctrine/dbal/pull/2929

**Comment by simobrazz** [comment] 2018-10-03 14:45
Any update on this? I'm struggling with this problem.

**Comment by duhamelstuff** [comment] 2019-04-16 18:57
> Any update on this? I'm struggling with this problem.

Hello, I had the same problem; I just drop manually the of the entity (database table) you need to change indexes (for example DROP INDEX actual_pk) and then re-run your doctrine update or query.

**Comment by goetas** [comment] 2020-04-09 20:28
Most probably related to https://github.com/doctrine/dbal/pull/3936

**Comment by tlorens** [comment] 2020-06-04 19:40
> As asked already twice, a test case is needed. The above are examples.

Eh, example would be fresh install of a Symfony project using Postgres.  Nothing special needs to be done. It just happens out of the box. Don't even need to drop any indexes.  Just make an entity change, generate a migration and there it goes.

**Comment by goetas** [comment] 2020-06-06 11:12
https://github.com/doctrine/dbal/pull/3936 is solving the issue (builds were green and tests oo), but is rather a big change and probably should be split in 2 or 3 different pull request.
Anyone willing to help?

**Comment by f-lombardo** [comment] 2023-02-20 18:06
The problem is still present (2.14.1). Is there any way to solve it?
Thanks in advance.

**Comment by johnpancoast** [comment] 2023-04-19 23:53
@f-lombardo, maybe check out @tlorens' [workaround above](https://github.com/doctrine/orm/issues/6271#issuecomment-483800877).

Until one of us writes a simple test case, the contributors cannot do much. I was super busy when I wrote this and didn't have time to go through doctrine's merge standards and all that at the time. I can't commit time for certain (I'm an awful human) but I'll try to do it unless somebody beats me to it. The test itself should be easy, and can likely just do something similar [to this](https://github.com/doctrine/orm/issues/6271#issuecomment-285892582) (just my assumption). Once that's written contributors can dig in.

**Comment by f-lombardo** [comment] 2023-04-30 20:43
Thank you @johnpancoast , see https://github.com/doctrine/dbal/pull/6025

**Comment by johnpancoast** [comment] 2023-05-03 21:12
Glad I could help... well, at least like .5% like 5 years ago :)

**Comment by f-lombardo** [comment] 2023-06-16 13:48
Fixed:
https://github.com/doctrine/dbal/pull/6025
