### ISSUE TITLE
Search-function in documentation broken

### ISSUE THREAD

**Issue by ghost** [doctrine/doctrine2#5871] opened 2016-06-13 03:53 UTC
Hello there,

it appears that the Search-function within the projects documentation-page is broken.
Visiting http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/ and entering s.th. like Select into the searchbox will bring you to https://readthedocs.org/search/project/?q=SELECT&selected_facets=project%3ADoctrine+ORM .

Issue https://github.com/doctrine/doctrine2/issues/5575 is not related IMHO as it refers to the RST.
This ticket refers to the actual documentation that is online.
The issue refers to trying to access the a stable documentation as well.
It is online (although the field still shows latest as being selected) but you have to access it through the url, access via page-element is broken.

Same holds true for some of the Documentation-links under http://www.doctrine-project.org/projects.html . e.g. http://docs.doctrine-project.org/projects/doctrine-couchdb-odm/en/latest/

Cheers

**Comment by wcerfgba** [comment] 2017-02-07 09:26
Bump, this is really annoying and has been broken for ages...

**Comment by Ocramius** [comment] 2017-02-07 09:27
Closing as duplicate of https://github.com/doctrine/doctrine-website-sphinx/issues/126

**Closed by Ocramius** 2017-02-07 09:27 UTC
