### ISSUE TITLE
2.17 broke bigint validations

### ISSUE THREAD

**Issue by gabplch** [doctrine/doctrine2#11089] opened 2023-11-28 13:56 UTC
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.17.*

#### Summary

Running `doctrine:schema:validate`

I suspect https://github.com/doctrine/orm/pull/10946

#### Current behavior
```php
[FAIL] The entity-class App\Entity\Foo mapping is invalid:
 * The field 'App\Entity\Foo#bar' has the property type 'int' that differs from the metadata field type 'string' returned by the 'bigint' DBAL type.
```

#### How to reproduce
```php
class Foo
{
    #[ORM\Column(type: Types::BIGINT)]
    protected int $bar = 1;
}
```

#### Expected behavior
No errors

**Comment by greg0ire** [comment] 2023-11-28 14:18
Duplicate of #11073

**Closed as not planned by greg0ire** 2023-11-28 14:18 UTC
