### ISSUE TITLE
Type error in getMaxResults, string returned instead of ?int

### ISSUE THREAD

**Issue by YetiCGN** [doctrine/doctrine2#9088] opened 2021-10-05 11:50 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 2.10.0

#### Summary

After updating from 2.9.6 to 2.10.0 we are getting type errors from Doctrine\ORM\Query,

#### Current behavior

Execute certain queries and `getMaxResults()` fails with:

```
Uncaught Error: Doctrine\ORM\Query::getMaxResults(): Return value must be of type ?int, string returned 
at /var/www/releases/20211005133026/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php:693)"} 
```

Downgrading to 2.9.6 gets rid of this problem. I don't know if all queries are affected or only some. Somewhere the `maxResults` class property is set to a string when it should always be a (nullable) integer.

#### How to reproduce

Install version 2.10.0 and run app or tests with a database query that retrieves maxResults.

**Comment by derrabus** [comment] 2021-10-05 12:03
Duplicate of #9086

**Closed as completed by derrabus** 2021-10-05 12:03 UTC

**Comment by YetiCGN** [comment] 2021-10-05 12:06
Only searched through open tickets, that's why I didn't find the existing ticket. Sorry!
