### ISSUE TITLE
automatically added unique index in OneToOne

### ISSUE THREAD

**Issue by poolerMF** [doctrine/doctrine2#5726] opened 2016-03-20 16:07 UTC
ClassMetadata -> _validateAndCompleteOneToOneMapping
code:

    ...
    if ($mapping['type'] === self::ONE_TO_ONE && ! $this->isInheritanceTypeSingleTable()) {
        if (count($mapping['joinColumns']) == 1) {
            if ( ! isset($mapping['id']) || ! $mapping['id']) {
                $joinColumn['unique'] = true;
            } else {
                $uniqueConstraintColumns[] = $joinColumn['name'];
            }
        }
    ...

I think it's not good to add automatically unique index on ONE_TO_ONE join... this make me mess in project ... If am I wrong, please tell me why :)

**Comment by poolerMF** [comment] 2016-03-20 16:15
or please tell me what to do, becouse I CAN NOT HAVE IT (uniqiue index in database)

**Comment by Ocramius** [comment] 2016-03-20 16:20
A one-to-one requires uniqueness on the association. If this breaks your constraints, that means that you are looking at a many-to-one association.

**Comment by poolerMF** [comment] 2016-03-20 16:25
in my project I must have ONE_TO_ONE .. relation exists or not
but I'm also using softDeleteable

so when I make ONE_TO_ONE  relation ... soft delete relation ... then I can not make new one

**Comment by Ocramius** [comment] 2016-03-20 16:26
Yeah, that's because soft-deletes are break integrity by design.
This has nothing to do with one-to-one by itself: you will have to redesign all your unique indexes anyway (making them span over the soft-delete keys).

Closing as `invalid`

**Closed by Ocramius** 2016-03-20 16:26 UTC
