### ISSUE TITLE
2.17 broke enum validations

### ISSUE THREAD

**Issue by simPod** [doctrine/doctrine2#11064] opened 2023-11-16 12:31 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.17.0

#### Summary

Running `doctrine:schema:validate --skip-sync`

I suspect https://github.com/doctrine/orm/pull/10946

#### Current behavior

`The field 'My\Ns\Entity\Foo#bar' has the property type 'My\Ns\Value\SomeStringBackedEnum' that differs from the metadata field type 'string' returned by the 'string' DBAL type.`

#### How to reproduce

```php
class Foo
    #[ORM\Column(type: Types::STRING, enumType: SomeStringBackedEnum::class)]
    private SomeStringBackedEnum $bar
}
```

#### Expected behavior

No errors

**Comment by greg0ire** [comment] 2023-11-16 12:52
Duplicate of https://github.com/doctrine/orm/issues/11037

**Closed as completed by greg0ire** 2023-11-16 12:52 UTC
