### ISSUE TITLE
blob typed field cannot be PHP strict type

### ISSUE THREAD

**Issue by ec-ecss** [doctrine/doctrine2#10012] opened 2022-08-28 13:24 UTC
BC Break    I don't know
Version     2.7.1-DEV

Current Behaviour :

Hydratation of a blob type (tested with row jpg data, and mariadb 10.8.3 ) is string when prePersist , but ressource type when hydrated from database.

Such a field in an entity must be currently mixed , and cannot be strict type.

**Comment by derrabus** [comment] 2022-09-01 08:28
Please provide steps to reproduce your problem.

**Comment by kiler129** [comment] 2022-12-24 21:55
@CaptainKant this looks to be by design, based on the DBAL code: https://github.com/doctrine/dbal/blob/63e513cebbbaf96a6795e5c5ee34d205831bfc85/src/Types/BlobType.php#L31

While you can keep resources in your entities, the default representation of binary data is a resource and not a UTF-8 ZE string. The DBAL `BlobType` is just adding a convenient feature to convert strings into proper binary resources on demand. In other words, you shouldn't be keeping binary blobs (and especially not large things like images) as strings in the first place.

**Comment by ec-ecss** [comment] 2022-12-26 16:27
@derrabus sorry it's not really a reproductible problem but a design issue and I think I described the necessary atomic concepts to describe it.
@kiler129 Yes of course the full binary hydratation is not pertinent. But the future of php is strict types should'nt it be a ressource from the start of the lifecycle of the entity ? The problem is that is both a string and a ressource.

**Comment by kiler129** [comment] 2022-12-26 20:28
@CaptainKant I fully agree with you - it should be a resource from the beginning. In one of the codebases I maintain which stores blobs in db we only accept a stream wrapper class, which in the entity is kept as a resource and no strings are ever allowed to leak there.

PHP deliberately (see "Type hint choices" in https://wiki.php.net/rfc/scalar_type_hints) does not provide a typehint for `resource` as by definition it's an opaque type which has its native subtype inside of it. The proper solution will require PHP to contain an object to represent rewindable and readable stream, which currently doesn't exists. Doctrine in such case could use it. The Doctrine itself cannot really remove string support and this magic conversion as this would be a BC break.

In your case I would recommend storing a resource or wrapped resource in your entity. Then in your setter you can verify that it's rewindable and `get_resource_type() === 'stream'`.

**Comment by derrabus** [comment] 2022-12-29 19:22
Okay, I get the problem now. We can't really do much about the fact that PHP does not allow you to type-hint a resource and that it still did not migrate stream resources to objects. I don't think that either the DBAL or the ORM should invent a container type for stream resources.

So what would be your proposed fix here? I'm tempted to close this issue as "won't fix", tbh.

**Comment by ec-ecss** [comment] 2022-12-30 09:45
You are the experts so I trust your decision and feedback ! 
That's not a so big deal anyway
Thanks :)

**Comment by kiler129** [comment] 2022-12-30 10:07
I think it's a "won't fix" but a note in docs could be useful in such a case. Users without knowing the internals are probably surprised how come their string magically turns into a resource ;)

**Comment by derrabus** [comment] 2022-12-30 10:44
Okay, closing then. If you feel like the documentation needs an update, feel free to submit a PR.

**Closed as not planned by derrabus** 2022-12-30 10:44 UTC
