### ISSUE TITLE
Second level cache, undefined method getCacheRegion

### ISSUE THREAD

**Issue by kubawerlos** [doctrine/doctrine2#6280] opened 2017-02-07 09:15 UTC
With Symfony 3.2.3 and ORM 2.5.6 (or master), when I remove cache configuration from entity I am getting:
```
Attempted to call an undefined method named "getCacheRegion" of class
"Doctrine\ORM\Persisters\Entity\BasicEntityPersister".
```
because method [getEntityPersister](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Cache/DefaultQueryCache.php#L110) is returning `Doctrine\ORM\Persisters\Entity\BasicEntityPersister` istead of `AbstractEntityPersister`.

**Comment by Ocramius** [comment] 2017-02-07 09:17
@kubawerlos can you try current `master`? I think it was fixed there, but not backported due to complexity

**Comment by lcobucci** [comment] 2017-02-07 09:18
I believe is a duplicate of #6124

**Comment by Ocramius** [comment] 2017-02-07 09:21
Closing as duplicate of #6124

**Closed by Ocramius** 2017-02-07 09:21 UTC
