### ISSUE TITLE
Version conflict

### ISSUE THREAD

**Issue by cnkt** [doctrine/doctrine2#6738] opened 2017-09-29 06:04 UTC
Hi there,

I'm aware of the new php 7.1 requirements and read the blog post about it. I use php 7.1.8 both on development and server. When i try to do composer update, i get this error:

```
  [Composer\DependencyResolver\SolverProblemsException]
    Problem 1
      - Installation request for doctrine/orm v2.5.9 -> satisfiable by doctrine/orm[v2.5.9].
      - doctrine/orm v2.5.9 requires doctrine/instantiator ~1.0.1 -> no matching package found.
    Problem 2
      - doctrine/orm v2.5.9 requires doctrine/instantiator ~1.0.1 -> no matching package found.
      - ramsey/uuid-doctrine 1.4.1 requires doctrine/orm ^2.5 -> satisfiable by doctrine/orm[v2.5.9].
      - Installation request for ramsey/uuid-doctrine ^1.2 -> satisfiable by ramsey/uuid-doctrine[1.4.1].
  Potential causes:
   - A typo in the package name
   - The package is not available in a stable-enough version according to your minimum-stability setting
     see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
  Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

Here is the contents of my composer.json:

```
"require": {
    "silex/silex": "~2.0",
    "doctrine/orm": "^2.5",
    "twig/twig": "~1.0",
    "symfony/console": "^3.0",
    "cakephp/collection": "dev-master",
    "knplabs/knp-menu": "^2.1@dev",
    "zendframework/zendframework1": "^1.12@dev",
    "phpoffice/phpexcel": "dev-master",
    "dflydev/doctrine-orm-service-provider": "^2.0",
    "ircmaxell/random-lib": "1.1.*@dev",
    "gedmo/doctrine-extensions": "2.4.*@dev",
    "jbroadway/urlify": "1.0.*@dev",
    "igorw/get-in": "^1.0@dev",
    "symfony/security": "^3.1",
    "symfony/security-bundle": "^3.1",
    "symfony/twig-bridge": "^3.0",
    "symfony/var-dumper": "^3.1",
    "symfony/debug-bundle": "^3.1",
    "symfony/translation": "^3.1",
    "sorien/silex-dbal-profiler": "~2.0",
    "sinasalek/silex-pagerfanta-provider": "1.0.*@dev",
    "fzaninotto/faker": "^1.6@dev",
    "kriswallsmith/assetic": "^1.3@dev",
    "tedivm/stash": "0.14.*",
    "league/flysystem": "^1.1@dev",
    "vlucas/phpdotenv": "^2.1@dev",
    "anahkiasen/underscore-php": "dev-master",
    "mouf/html.widgets.statsgrid": "~1.0",
    "codeguy/upload": "dev-master",
    "imagine/imagine": "~0.5.0",
    "leongkui/silex-php-redis": "*",
    "phpmailer/phpmailer": "dev-master",
    "swiftmailer/swiftmailer": "^5.4",
    "guzzlehttp/guzzle": "^6.1",
    "illuminate/encryption": "^5.1",
    "phpunit/php-timer": "~1.0",
    "elasticsearch/elasticsearch": "~2.0@beta",
    "mk-j/php_xlsxwriter": "dev-dev",
    "fabpot/goutte": "^3.1",
    "cakephp/chronos": "@stable",
    "beberlei/DoctrineExtensions": "^1.0",
    "akeneo-labs/spreadsheet-parser": "^1.2",
    "php-amqplib/php-amqplib": "2.6.*",
    "sendgrid/sendgrid": "~5.0.4",
    "aura/payload": "^3.0",
    "box/spout": "^2.5",
    "sentry/sentry": "^1.1",
    "datadog/php-datadogstatsd": "0.3.*",
    "friendsofphp/php-cs-fixer": "^1.12",
    "ramsey/uuid-doctrine": "^1.2",
    "sabre/xml": "^2.0",
    "zendframework/zendxml": "^1.0",
    "saxulum/saxulum-doctrine-orm-manager-registry-provider": "^3.1",
    "saxulum/saxulum-console": "~3.1",
    "cboden/ratchet": "0.3.*",
    "react/zmq": "0.2.*|0.3.*",
    "mongodb/mongodb": "^1.2@dev",
    "saxulum/saxulum-doctrine-orm-commands": "dev-master",
    "sorien/silex-pimple-dumper": "~2.0",
    "predis/service-provider": "^2.0@dev",
    "symfony/cache": "^4.0@dev"
  },
```

My minimum-stability is dev.

Thanks in advance.

**Comment by Ocramius** [comment] 2017-09-29 06:17
See discussion on https://github.com/doctrine/doctrine2/commit/0ec9e53c8d43d02c824dc4bfc8826a5e6e1d66e2 please

**Comment by cnkt** [comment] 2017-09-29 06:24
Hi, thanks for the quick reply.

I changed my orm dependency to 2.5.11 but still no luck:
```

[Composer\DependencyResolver\SolverProblemsException]
    Problem 1
      - Installation request for doctrine/orm 2.5.11 -> satisfiable by doctrine/orm[v2.5.11].
      - doctrine/orm v2.5.11 requires doctrine/common >=2.5-dev,<2.9-dev -> no matching package found.
    Problem 2
      - doctrine/orm v2.5.11 requires doctrine/common >=2.5-dev,<2.9-dev -> no matching package found.
      - ramsey/uuid-doctrine 1.4.1 requires doctrine/orm ^2.5 -> satisfiable by doctrine/orm[v2.5.11].
      - Installation request for ramsey/uuid-doctrine ^1.2 -> satisfiable by ramsey/uuid-doctrine[1.4.1].
  Potential causes:
   - A typo in the package name
   - The package is not available in a stable-enough version according to your minimum-stability setting
     see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
  Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by Ocramius** [comment] 2017-09-29 06:35
The fact that doctrine/common is not visible is extremely bizarre. Can you
see if (temporarily) deleting the `composer.lock` helps?

**Comment by cnkt** [comment] 2017-09-29 06:37
```
# cnkt at cmhpc-2.local in ~/Downloads/devmac/OptDoc on git:master ✖︎ [9:23:46]
→ rm composer.lock

# cnkt at cmhpc-2.local in ~/Downloads/devmac/OptDoc on git:master ✖︎ [9:36:34]
→ php composer.phar update --prefer-dist
    1/2:	http://packagist.org/p/provider-latest$01cbeaac8fc30c58cce1894bd241f163c617fc9cb52f54f5444d484cc4ad5d34.json
    2/2:	http://packagist.org/p/provider-2017-07$2128fe4d2b143069d0b2a0365f6affd55e7d7cbb0210d0a13fcdf92d6256fca8.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
Loading composer repositories with package information
Updating dependencies (including require-dev)


  [Composer\DependencyResolver\SolverProblemsException]
    Problem 1
      - Installation request for doctrine/orm 2.5.11 -> satisfiable by doctrine/orm[v2.5.11].
      - doctrine/orm v2.5.11 requires doctrine/common >=2.5-dev,<2.9-dev -> no matching package found.
    Problem 2
      - doctrine/orm v2.5.11 requires doctrine/common >=2.5-dev,<2.9-dev -> no matching package found.
      - ramsey/uuid-doctrine 1.4.1 requires doctrine/orm ^2.5 -> satisfiable by doctrine/orm[v2.5.11].
      - Installation request for ramsey/uuid-doctrine ^1.2 -> satisfiable by ramsey/uuid-doctrine[1.4.1].
  Potential causes:
   - A typo in the package name
   - The package is not available in a stable-enough version according to your minimum-stability setting
     see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
  Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
```

sorry, still no success.

**Comment by cnkt** [comment] 2017-09-29 06:41
No problem. Thanks for your help. it's really appreciated.

**Comment by Ocramius** [comment] 2017-09-29 06:46
@cnkt re-opening here: please close once a resolution is found in the related issue (once you have one)

**Comment by cnkt** [comment] 2017-09-29 07:04
Sorry. Ok, i'm opening an issue on composer.

**Comment by cnkt** [comment] 2017-09-29 07:05
Related issue: https://github.com/composer/composer/issues/6712

**Comment by akomm** [comment] 2017-10-19 12:53
I had similar issue with doctrine/inflector not being seen by composer. 
I cleared the cached packages - issue remained
I removed the lock file - issue remained

This fixed it:
I set manually the third party dependencies in the root composer.json untill all errors were gone.
then I reverted the composer.json, remove lock file, deleted vendor.

After that composer install worked correctly.
I did clone doctrine/orm in another folder and composer install worked right ahead, without manually including dependencies.

I think composer stored something incorrectly inside its local settings in .composer. And it were not the cached packages.

**Comment by ostrolucky** [comment] 2018-08-06 22:56
This is going nowhere. Linked issue has been closed and since this is clearly composer issue and we didn't receive any updates in a while, I'm going to close this as well. Still, feel free to comment here if you still feel this is issue in a doctrine repository and have any info helping to reproduce or troubleshoot this.

**Closed by ostrolucky** 2018-08-06 22:56 UTC
