### ISSUE TITLE
second-level-cache, entity-hydrator throws exception

### ISSUE THREAD

**Issue by floriansemm** [doctrine/doctrine2#5808] opened 2016-05-04 09:32 UTC
I have the following entity:

``` php
/**
 * Geoinformation
 *
 * @ORM\Table(...)
 * @ORM\Entity(...)
 * @ORM\Cache(usage="NONSTRICT_READ_WRITE", region="geoinformation_region")
 */
class Geoinformation
{
    // more properties

    /**
     * @var GeoinformationMetaData
     *
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\GeoinformationMetaData", inversedBy="geoinformation", cascade={"persist"})
     * @ORM\JoinColumn(name="geoinformation_meta_data_id", referencedColumnName="id")
     * @ORM\Cache(usage="NONSTRICT_READ_WRITE", region="geoinformation_region")
     */
    private $metaData;
}
```

Creating and persisting of new `GeoinformationMetaData` objects works fine. When I query the database I get the following error:

```
Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Undefined index: targetToSourceKeyColumns" at /project/vendor/doctrine/orm/lib/Doctrine/ORM/Cache/DefaultEntityHydrator.php line 106 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: targetToSourceKeyColumns at /project/vendor/doctrine/orm/lib/Doctrine/ORM/Cache/DefaultEntityHydrator.php:106
```

I use doctrine `v2.5.4` with symfony `v3.0.5`.

**Comment by okwinza** [comment] 2016-06-24 02:19
same thing with enabled second level cache, sf 2.8.7, doctrine 2.5.4

Any ideas?

**Comment by Ocramius** [comment] 2016-06-24 02:48
Does this also affect master?

**Comment by okwinza** [comment] 2016-06-24 12:22
Master seems fine.

**Comment by Ocramius** [comment] 2016-07-12 15:04
Can anyone verify what commit fixes this issue, and link it up with what this issue duplicates?

**Comment by yceruto** [comment] 2016-07-12 16:42
@floriansemm, @okwinza the ["Association cache definition"](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/second-level-cache.html#association-cache-definition) documentation has a note:

> Note: for this to work, the target entity must also be marked as cacheable.

Please, you could to check if this error still occurs adding `@ORM\Cache(usage="NONSTRICT_READ_WRITE", region="geoinformation_region")` to `AppBundle\Entity\GeoinformationMetaData` target entity ??

**Comment by Majkl578** [comment] 2016-07-12 19:25
Repro test case here: https://gist.github.com/Majkl578/61731254ea9d36f2f32778d357ff4f5b
Bisected fix to commit e64f44ec9be28445eb340b9870f4b431baf554de (doesn't apply cleanly to 2.5.4 though).

**Comment by floriansemm** [comment] 2016-07-14 09:08
@yceruto the error was caused by an other relation. Everything is fine now.

**Comment by lcobucci** [comment] 2016-09-19 13:52
> @yceruto the error was caused by an other relation. Everything is fine now.

Does it means that this issue can be closed?

**Comment by Ocramius** [comment] 2017-02-07 09:21
Closing as duplicate of #6124 unless anybody can create a different failing test scenario (in such case, I'll re-open).

**Closed by Ocramius** 2017-02-07 09:21 UTC
Labels: Bug, Duplicate
