### ISSUE TITLE
EntityManager::find return type is just object in the lexer. 

### ISSUE THREAD

**Issue by axelcho** [doctrine/doctrine2#6841] opened 2017-11-22 14:25 UTC
I would like to force strict class check on find return. It is theoretically possible to return anything as a result of EntityManger::find 

Also, on EntityManager::persist($entity), there is no type hint on $entity, and theoretically I can pass any object to the entity.

**Comment by coudenysj** [comment] 2017-11-22 14:40
A good solution is to use Repositories (http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/working-with-objects.html#custom-repositories) for that.

You can implement a "find" method there (which is basically the same as doing it in the EM).

As for the persist type hint, you could add a "save" method to the Repository with a type hint.

**Comment by Ocramius** [comment] 2017-11-22 14:42
@axelcho this is because the ORM actually accepts any object, and will fail only when the given object is not mapped.

This is by design, as PHP has no better type system to work with.

Closing as `invalid`

**Closed by Ocramius** 2017-11-22 14:42 UTC

**Comment by Majkl578** [comment] 2017-12-06 00:47
Note: This will be improved by adding native `object` type in develop/3.0 where we already require PHP 7.2. Siínce PHP has no generics, nothing better could be done here.
