### ISSUE TITLE
[Bug] Attempting to change readonly property when removing an entity

### ISSUE THREAD

**Issue by pattisahusiwa** [doctrine/doctrine2#9816] opened 2022-06-03 19:52 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.12.2
| PHP | 8.1.6

#### Summary

When removing an entity with read-only `$id`, `\LogicException` is thrown

#### Current behavior

`\LogicException` is thrown

![bug](https://user-images.githubusercontent.com/11484016/171938422-43cc07d6-f3a4-46fe-881f-a8593e760442.png)

#### How to reproduce

```php
#[ORM\Entity]
class Entity
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    public readonly int $id;
}
```
```php
$em->remove($entity);
$em->flush();
```

#### Expected behavior

No error.

**Comment by greg0ire** [comment] 2022-06-03 21:03
Duplicate of #9538

**Closed as completed by greg0ire** 2022-06-03 21:03 UTC
