### ISSUE TITLE
Commit order reversed?

### ISSUE THREAD

**Issue by olivier1980** [doctrine/doctrine2#10897] opened 2023-08-09 14:07 UTC
Since release v2.16 this line of code won't save the entities in order of the loop anymore:

```
 foreach ($importDossier->getKlanten() as $klant) {
          $klant->setIsActive(true);
          $this->entityManager->persist($klant);
}
```

The last line to be executed will get an earlier id in the DB than the first iteration of the loop...which seems weird. Is this expected behaviour?

I noticed work was done on the commit order here: https://github.com/doctrine/orm/pull/10547

**Comment by olivier1980** [comment] 2023-08-09 14:22
Apparently this is now the new behaviour: 

```
    Do not make any assumptions in your code about the number of queries
    it takes to flush changes, about the ordering of ``INSERT``, ``UPDATE``
    and ``DELETE`` queries or the order in which entities will be processed.
```

and they don't consider it a BC breaking change lol

**Comment by greg0ire** [comment] 2023-08-09 20:29
Damn right we don't! And the paragraph you're quoting does not document new behavior. It merely newly documents that using the ORM does not and never did guarantee any particular insertion order.

**Comment by derrabus** [comment] 2023-08-10 09:47
FTR, duplicate of #10864

**Closed as not planned by derrabus** 2023-08-10 09:47 UTC
