### ISSUE TITLE
BC : Type-hint of annotation construct of Doctrine\ORM\MappingManyToOne

### ISSUE THREAD

**Issue by ohaag** [doctrine/doctrine2#8783] opened 2021-06-24 10:44 UTC
Hello, 

Isn't there a Breaking change introduced with this [MR](https://github.com/doctrine/orm/pull/8266/files#diff-790d3cacd00cac9337da12d655fb50429091d836071bc62952c55561daae157aR63) which have been missed ?
The highlighted line type-hint the cascade annotation into an array.
But it was previously possible to write `cascade="all"`.
Now, it generated this error : 
`Argument 2 passed to Doctrine\ORM\Mapping\ManyToOne::__construct() must be of the type array or null, string given, called in /Users/ohaag/workspace/mist/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 971`

Only `cascade={"all"}` works. 

This should be noticed in upgrade documentation.

N.B : it could have further impact as the construct have been added for many Class in the same time. I only tested the cascade issue.

**Comment by greg0ire** [comment] 2021-06-24 19:09
Duplicate of #8720

**Closed as completed by greg0ire** 2021-06-24 19:09 UTC
