### ISSUE TITLE
toIterable() Exception -  Iterating a query with mixed results (using scalars) is not supported

### ISSUE THREAD

**Issue by sergeysrabionyan** [doctrine/doctrine2#8562] opened 2021-03-26 08:17 UTC
When I try to iterate over the queryBuilder toIterable() method I get an error "Iterating a query with mixed results (using scalars) is not supported", when I use the "deprecated" method iterate () I get the correct result.

 Can I repeat the behavior of the iterate () method and make it not deprecated?

**Comment by beberlei** [comment] 2021-03-26 08:23
We have not managed to find a way to support it yet, but if you do of course we will accept it.

**Comment by eigan** [comment] 2021-07-15 09:20
Duplicate of #8520

**Closed as completed** 2021-07-15 15:28 UTC
