### ISSUE TITLE
ManyToManyPersister fails to remove join table entry if there is multiple join columns

### ISSUE THREAD

**Issue by NicolaF** [doctrine/doctrine2#6991] opened 2018-01-18 11:05 UTC
this is due to a typo in `\Doctrine\ORM\Persisters\Collection\ManyToManyPersister::getDeleteSQLParameters`:

```
        foreach ($mapping['relationToSourceKeyColumns'] as $columnName => $refColumnName) {
            $params[] = isset($sourceClass->fieldNames[$refColumnName])
                ? $identifier[$sourceClass->fieldNames[$refColumnName]]
                : $identifier[$sourceClass->getFieldForColumn($columnName)];
        }

```

It should be `$sourceClass->getFieldForColumn($refColumnName)`, as `$columnName` is the join table column, not the entity table column.

**Comment by Ocramius** [comment] 2018-01-18 12:06
Closing as duplicate of https://github.com/doctrine/doctrine2/pull/6992

**Closed by Ocramius** 2018-01-18 12:06 UTC

**Comment by NicolaF** [comment] 2018-01-19 17:11
Hi @Ocramius 
See #6997 for PR on the 2.6 branch

**Comment by Ocramius** [comment] 2018-01-20 04:22
@NicolaF thanks!
