### ISSUE TITLE
[Documentation] Documentation of Types Mapping Matrix does not have footnotes

### ISSUE THREAD

**Issue by FuzzyPones** [doctrine/doctrine2#7396] opened 2018-09-11 09:53 UTC
|    Q        |   A
|------------ | -----
| Version     | 2.8

### Support Question

See:
https://www.doctrine-project.org/projects/doctrine-dbal/en/2.8/reference/types.html#mapping-matrix

> Please also notice the mapping specific footnotes for additional information.

There aren't any

**Comment by Majkl578** [comment] 2018-09-23 04:50
Thanks for spotting this - it's a duplicate of already known https://github.com/doctrine/doctrine-website/issues/47 since we migrated to a new website.

**Closed** 2018-09-23 04:51 UTC
Labels: Documentation, Duplicate

**Comment by Majkl578** [comment] 2018-09-23 04:52
For now, you can view the page on GitHub directly, it'll render footnotes as well: https://github.com/doctrine/dbal/blob/master/docs/en/reference/types.rst#mapping-matrix
