### ISSUE TITLE
Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_x does not exist

### ISSUE THREAD

**Issue by ro0NL** [doctrine/doctrine2#11230] opened 2024-02-07 11:46 UTC
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no?

#### Summary

Hi,

We see exception `Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_205 does not exist` every now&then.

It comes from https://github.com/doctrine/orm/blob/ccfc97c32f63aaa0988ac6aa42e71c5590bb794d/lib/Doctrine/ORM/UnitOfWork.php#L485

Im looking for ways to debug it, but i'm worried the original exception is hidden.

Im wondering if we could try/catch it and let the original exception bubble up.

**Comment by derrabus** [comment] 2024-02-07 12:08
I'm guessing this is MySQL? Do you by change perform any DDL operations (like `CREATE TABLE` or `TRUNCATE`) inside that transaction which would cause MySQL to commit the whole thing?

**Comment by ro0NL** [comment] 2024-02-07 12:24
> I'm guessing this is MySQL? 
> Do you by change perform any DDL operations

Correct, and not that i'm aware of :sweat_smile: 

Since we already had a custom connection middleware, i've added this gem to `exec()` for now:

```
        if (str_starts_with($sql, 'ROLLBACK TO SAVEPOINT ')) {
            // @see https://github.com/doctrine/orm/issues/11230
            try {
                return parent::exec($sql);
            } catch (\Throwable $e) {
                $this->logger->warning('Failed to rollback to savepoint', ['exception' => $e]);

                return 0;
            }
        }

        return parent::exec($sql);
```

Will monitor prod today to see if it reveals our issue :+1:

**Comment by ZhukV** [comment] 2024-02-07 12:27
We receive same problem too on our applications. We try to investigate this problem with any scenarios, but can't reproduce locally. @ro0NL , please provide info about you error after you investigate. Thank.

**Comment by ro0NL** [comment] 2024-02-07 12:35
could this be concurrency related perhaps?

**Comment by ZhukV** [comment] 2024-02-07 12:48
From our research: yes, and only in concurrency. In one process (thread) all OK.

We have custom component (scheduler), and have few commands for cleanup items. But first command run delete sql with datetime range (globally cleanup), second command run delete with specific id (cleanup for specific scheduler).

First process:

```
DELETE FROM scheduler_items WHERE execute_at >= ....
```

Second process:

```
START TRANSACTION;
SELECT * FROM scheduler_items WHERE id = ... FOR UPDATE;
SAVEPOINT savepoint_1;
DELETE FROM scheduler_items WHERE id = ...;
ROLBACK TO SAVEPOINT savepoint_1; // Delete query throw error, but we see only - SAVEPOINT does not exist ;(
```

I think (but not sure), what problem in use lock mechanism. In second process we lock row, but in first process we remove without use lock mechanism. After delete on second process, row not found in DB, and it throw error. But I'm not at all sure about this. We try to reproduce locally, but not catch error ;( 

Note: you temporary solution with use middleware - very nice. I think we try to use it too.

**Comment by ro0NL** [comment] 2024-02-07 14:52
nope, i cant figure this out. After try/catching `commit/rollback/release savepoint/rollback to savepoint` in connection middleware our messages start succeeding, while only producing logs:

```
Failed SQL: RELEASE SAVEPOINT DOCTRINE_2
Failed to commit: There is no active transaction
```

regarding concurrency, is this simple as including a process ID modifer or so in the savepoint name? `DOCTRINE_<process/group>_<counter>` @greg0ire maybe?

**Comment by ZhukV** [comment] 2024-02-07 16:00
I can reproduce it locally :)

```sql
DROP TABLE IF EXISTS tbl1 ;
DROP TABLE IF EXISTS tbl2 ;

CREATE TABLE tbl1
(
    id VARCHAR(255) PRIMARY KEY,
    b  VARCHAR(255)
);
CREATE TABLE tbl2
(
    id VARCHAR(255) PRIMARY KEY,
    b  VARCHAR(255)
);

INSERT INTO tbl1 (id, b)
VALUES (1, 1);
INSERT INTO tbl2 (id, b)
VALUES (1, 1);
```

### Test without savepoint

| Session #1                            | Session #2                            | Description                         |
|---------------------------------------|---------------------------------------|-------------------------------------|
| `START TRANSACTION;`                  |                                       |                                     |
| `UPDATE tbl1 SET b = 1 WHERE id = 1;` |                                       |                                     |
|                                       | `START TRANSACTION;`                  ||
|                                       | `UPDATE tbl2 SET b = 1 WHERE id = 1;` ||
| `UPDATE tbl2 SET b = 1 WHERE id = 1;` |                                       | wait lock (locked in session #2)    |
|                                       | `UPDATE tbl1 SET b = 1 WHERE id = 1;` | Deadlock (recursion)                |
| `COMMIT;`                             |                                       |                                     |
|                                       | `ROLLBACK;`                           | Entity manager call `rollback` |


### Test with savepoints

| Session #1                            | Session #2                            | Description                            |
|---------------------------------------|---------------------------------------|----------------------------------------|
| `START TRANSACTION;`                  |                                       |                                        |
| `UPDATE tbl1 SET b = 1 WHERE id = 1;` |                                       |                                        |
|                                       | `START TRANSACTION;`                  ||
| | `SAVEPOINT savepoint_1;`              |                                        |
|                                       | `UPDATE tbl2 SET b = 1 WHERE id = 1;` ||
| `UPDATE tbl2 SET b = 1 WHERE id = 1;` |                                       | wait lock (locked in session #2)       |
|                                       | `UPDATE tbl1 SET b = 1 WHERE id = 1;` | Deadlock (recursion)                   |
| `COMMIT;`                             |                                       |                                        |
|                                       | `ROLLBACK TO savepoint_1;`            | Entity manager call `rollback` (ERROR) |


Sorry for more SQL.

By documentation from MySQL https://dev.mysql.com/doc/refman/8.0/en/innodb-error-handling.html DEADLOCK will lead rollback the entire transaction. As result, in session #2 after deadlock error we CANNOT execute `rollback to savepoint`, because MySQL roll back ENTIRE transaction, but by default logic in `EntityManager::flush (UnitOfWork::commit)` - after catched error system try to execute `rollback`.

P.S. This is only possible if save points are enabled. If savepoints are disabled (by default in `Dbal 3.*`) - developers not see this error, because system not open savepoints.

**Comment by ro0NL** [comment] 2024-02-07 16:33
nice findings! does that mean mysql+savepoints+concurrency is a dead-end?

**Comment by ZhukV** [comment] 2024-02-07 17:14
Yes, but it's not one scenarios, if we only consider MySQL. I found two pages, where MySQL rollback entire transaction:

* https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html
* https://dev.mysql.com/doc/refman/8.0/en/innodb-error-handling.html

Maybe MySQL have other situations where it is not a SQL that is rolled back, but an entire transaction.

But I think this is a normal flow for the database level and especially MySQL. And root cause in development layer of application. Just my opinion:

1. Why use savepoints for simple applications?
2. If savepoints are required for application, then developer should total control it.
3. Maybe better will be detect savepoint error on dbal layer and clear transaction info (imitate full rollback).
4. other...

**Comment by ro0NL** [comment] 2024-02-07 17:34
> If savepoints are required for application, then developer should total control it.

but we cant in case of concurrency, because "mysql". Note im not an infrastructural expert ;)

also IIUC doctrine/orm:^3 will enforce savepoints either way

i just thought it was nice to have command execution wrapped in a transaction by default

i think i'll rewrite our transaction middleware so that it only creates an outer transaction, and thus avoid nested savepoints in this case.

**Comment by ZhukV** [comment] 2024-02-07 18:25
> i just thought it was nice to have command execution wrapped in a transaction by default

For me, it's very good idea, and we use this solution for all our applications (but use use our custom `#Transactional` attribute).

> i think i'll rewrite our transaction middleware so that it only creates an outer transaction, and thus avoid nested savepoints in this case.

I think is impossible without changes in `dbal/orm` because:

* if wrap via ORM (flush), UnitOfWork always call `beginTransaction` inside `commit` method.
* if wrap via DBAL, in future releases savepoints are be enabled by default and cannot able to disable.

But I may not understand your thoughts :) I’ll be looking forward to it.

**Comment by ZhukV** [comment] 2024-02-07 21:56
I write simple PHP script for illustrate problem (with deadlock):

```php
<?php

namespace Acme;

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\DriverManager;
use Doctrine\DBAL\Tools\DsnParser;
use Symfony\Component\Process\Process;

include_once __DIR__.'/vendor/autoload.php';

define('PHP_EXECUTABLE', '/usr/local/bin/php');
define('DATABASE_URL', 'pdo-mysql://lottery-user:Q1w2e3r4@lottery-db:3306/lottery?serverVersion=8.0');

function isUseSavepoints(): bool
{
    $argv = $_SERVER['argv'] ?? [];

    return ($argv[1] ?? null) === 'savepoint' || ($argv[2] ?? null) === 'savepoint';
}

function makeConnection(): Connection
{
    $dsnParser = new DsnParser();
    $connectionParams = $dsnParser
        ->parse(DATABASE_URL);

    $connection = DriverManager::getConnection($connectionParams);
    $connection->setNestTransactionsWithSavepoints(isUseSavepoints());

    return $connection;
}

function prepareDb(Connection $connection): void
{
    $connection->executeStatement('DROP TABLE IF EXISTS tbl1');
    $connection->executeStatement('DROP TABLE IF EXISTS tbl2');

    $connection->executeStatement('CREATE TABLE tbl1 (id VARCHAR(255), b VARCHAR(255))');
    $connection->executeStatement('CREATE TABLE tbl2 (id VARCHAR(255), b VARCHAR(255))');

    $connection->executeStatement('INSERT INTO tbl1 (id, b) VALUES (1, 1)');
    $connection->executeStatement('INSERT INTO tbl2 (id, b) VALUES (1, 1)');
}

$process = $argv[1] ?? '';

if ('' === $process || 'savepoint' === $process) {
    $connection = makeConnection();
    prepareDb($connection);

    print 'Successfully initialize test tables in DB.'.PHP_EOL.PHP_EOL;

    /** @var Process[] $processes */
    $processes = [];

    $processes['session 1'] = new Process([
        PHP_EXECUTABLE,
        __FILE__,
        'first',
        isUseSavepoints() ? 'savepoint' : '',
        '&',
    ]);

    $processes['session 2'] = new Process([
        PHP_EXECUTABLE,
        __FILE__,
        'second',
        isUseSavepoints() ? 'savepoint' : '',
        '&',
    ]);

    foreach ($processes as $session => $process) {
        $process->start(function ($type, $output) use ($session) {
            print '---'.$session.'---'.PHP_EOL;
            print $output.PHP_EOL;
            print '<--'.$session.'--- END'.PHP_EOL;
        });
    }

    foreach ($processes as $process) {
        $process->wait();
    }
}

function waitBetweenProcesses(): void
{
    usleep(1 * (10 ** 6));
}

if ('first' === $process) {
    $connection = makeConnection();

    $connection->beginTransaction();
    $connection->executeStatement('UPDATE tbl1 SET b = 1 WHERE id = 1');

    print 'Session #1: Success execute start transaction and update tbl1.'.PHP_EOL;
    waitBetweenProcesses();

    print 'UPDATE tbl2'.PHP_EOL;
    $connection->executeStatement('UPDATE tbl2 SET b = 1 WHERE id = 1;');
}

if ('second' === $process) {
    usleep(0.5 * (10 ** 6)); // Wait 0.5 second (timeout between processes - 0.5 second).
    $connection = makeConnection();

    $connection->beginTransaction();
    $connection->executeStatement('UPDATE tbl2 SET b = 1 WHERE id = 1');

    print 'Session #2: Success execute start transaction and update tbl2.'.PHP_EOL;
    waitBetweenProcesses();

    print 'UPDATE tbl1'.PHP_EOL;

    if (isUseSavepoints()) {
        try { // This block really imitate EntityManager::flush inside opened transaction (inside DoctrineTransactionMiddleware as an example)
            $connection->beginTransaction();
            $connection->executeStatement('UPDATE tbl1 SET b = 1 WHERE id = 1;');
        } catch (\Throwable $error) {
            $connection->rollBack();
        }
    } else {
        $connection->executeStatement('UPDATE tbl1 SET b = 1 WHERE id = 1;');
    }
}
```

You can run:

```shell
php script.php                 # without savepoints
php script.php savepoint       # with savepoints
```

If we run without savepoints, we see real error - deadlock. But if we run with savepoints we see error - `savepoint does not exist`. 

I am not an expert in Doctrine, much less in DBAL, but maybe better will be throw real (origin) error on DBAL side (because in any cases origin error is deadlock from MySQL)?

P.S. Sorry for big PHP code...

**Comment by ro0NL** [comment] 2024-02-08 08:20
both errors are real to me :sweat_smile: i mean, in both cases "concurrent mysql" is the issue

im not sure how to deal with it on DBAL/ORM side either. That's future work for maintainers :)

for now im going to opt-out our command from running transactional (it's not a real requirement for this specific case), that solves the issue as well. Im not really happy with try/catching the commit/rollback flow really, even though the "return bool" API allows for it.

eventually maybe just take some error percentage for granted as well, but time will tell.

**Comment by derrabus** [comment] 2024-02-08 08:53
> also IIUC doctrine/orm:^3 will enforce savepoints either way

No, the ORM is not aware of the savepoint setting and does not enforce it.

**Comment by derrabus** [comment] 2024-02-08 08:57
So, if I understand the issue correctly, the DBAL does not detect a deadlock correctly and thus assumes a wrong transaction nesting level? This needs to be fixed in the DBAL then.

**Closed as completed** 2024-02-09 13:30 UTC

**Comment by ro0NL** [comment] 2024-02-09 14:27
also if you're tracking transaction level in custom connection middleware, the count will be totally broken after switching to savepoints.

I dont understand why it goes via exec(), rather than being an implementation detail of beginTransaction/commit/rollback.

**Comment by derrabus** [comment] 2024-02-09 14:30
> also if you're tracking transaction level in custom connection middleware, the count will be totally broken after switching to savepoints.

Because without savepoints, the transaction level is pretty much a boolean?

**Comment by ro0NL** [comment] 2024-02-09 14:31
the level is plussed either way

this will break https://github.com/symfony/symfony/blob/d995693bb816310795fd9090b66bf8213d053021/src/Symfony/Bridge/Doctrine/Middleware/Debug/DBAL3/Connection.php#L28

**Comment by ro0NL** [comment] 2024-02-09 14:32
AFAIK nested savepoints should increase the transaction level

**Comment by ro0NL** [comment] 2024-02-09 14:38
it breaks compatibility

will disable use_savepoints for as long as possible :D

**Comment by rmikalkenas** [comment] 2024-02-28 08:31
I'm facing the exact same issue. 
Since the task has been closed without clear summary, I guess the correct way would be to disable savepoints.
Is there going to be any fixes for it?

**Comment by greg0ire** [comment] 2024-04-24 21:22
Just read the full thread while trying to find out what @ro0NL meant by "eg. due `SAVEPOINT DOCTRINE_2 does not exist`" in #11423 … wouldn't the next logical step be to file a DBAL bug report?

**Comment by antman3351** [comment] 2024-05-07 13:31
Shouldn't the connection ( if it's being used with MySql/MariaDB ) still decrement the `transactionNestingLevel` if it encounters a save point doesn't exist error ( code 1305 https://dev.mysql.com/doc/connectors/en/connector-j-reference-error-sqlstates.html ). Otherwise the Connection class is broken from then onwards. instead if it decrements the nesting level the code can still recover like this simplified example:

```PHP
<?php
try
{
    // Top level transaction...
    $connection->beginTransaction();

    // ... lets pretend this is in annother function that is clueless that it's inside a transaction...
    try
    {
        // Save point
        $connection->beginTransaction();

        // ... lets pretend a query here causes a deadlock

        $connection->commit();
    }
    catch ( \Exception $excepion )
    {
        // This will throw an exception ( because the save point doesn't exist )
        //  that will keep bubbling until it's caught by the top level catch
        $connection->rollBack();
    }

    $connection->commit();
}
catch ( \Exception $excepion )
{
    // <b>IF</b> DBAL connection decremented the nesting level earlier
    //  this call wouldn't cause an exception even if there's nothing to rollback and our code can carry on...
    $connection->rollBack();
}
```

**Comment by nikophil** [comment] 2024-12-06 07:35
Hi @derrabus @ro0NL 

> So, if I understand the issue correctly, the DBAL does not detect a deadlock correctly and thus assumes a wrong transaction nesting level? This needs to be fixed in the DBAL then.

we exactly having this problem: a deadlock occurs because of concurrency (with symfony/messenger) and while doing the rollback, we're having a `SAVEPOINT DOCTRINE_x does not exist`

I see that this issue is closed, but I cannot find any other issue that track the problem with savepoints in dbal + mconcurrency + mysql :thinking:  I found [this PR](https://github.com/doctrine/orm/pull/11646) which fixes the problem that errors in rollback did hide the original error, but nothing that fixes this specific issue. Do you have any hints, please? :pray:

**Comment by Tofandel** [comment] 2025-04-10 20:40
I am hitting the same issue on the bootstrap of unit test

```php
<?php

use App\Kernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Dotenv\Dotenv;

require dirname(__DIR__).'/vendor/autoload.php';

if (file_exists(dirname(__DIR__).'/config/bootstrap.php')) {
    require dirname(__DIR__).'/config/bootstrap.php';
} elseif (method_exists(Dotenv::class, 'bootEnv')) {
    (new Dotenv())->bootEnv(dirname(__DIR__).'/.env');
}

$kernel = new Kernel('test', true); // create a "test" kernel
$kernel->boot();

$application = new Application($kernel);
$application->setAutoExit(false);

$commands = [
    ['command' => 'doctrine:schema:drop', '--force' => true, '--full-database' => true, '--quiet' => true],
    //['command' => 'doctrine:schema:create'],
    ['command' => 'doctrine:migrations:migrate', '--no-interaction' => true],
    ['command' => 'doctrine:fixtures:load', '--append' => true, '-v'],
];

foreach ($commands as $command) {
    $application->run(new ArrayInput(is_array($command) ? $command : [
        'command' => $command,
    ]), new ConsoleOutput());
}
```
If I use `doctrine:migrations:migrate` then I hit the issue during the fixtures:load, if I use `doctrine:schema:create` then no issue

The database is in the same state after `doctrine:migrations:migrate` or `doctrine:schema:create`

If I make all migrations non transactional with

```php
    public function isTransactional(): bool
    {
        return false;
    }
```

Then I don't get the issue. (Though I get a warning  Exception in third-party event subscriber: There is no active transaction, but that seems to be because of the '--full-database' option)

Why is a previous command influencing the state of a future command?
