### ISSUE TITLE
Doctrine aliasing issue when column name starts with number

### ISSUE THREAD

**Issue by CheeseBites** [doctrine/doctrine2#7338] opened 2018-08-07 19:50 UTC
If the column name starts with a number the querybuilder doesn't wrap the alias in quotes,

Error returns:
`An exception occurred while executing 'SELECT t0_.AA AS AA_0, t0_.BB AS BB_1, t0_.[12AA] AS 12AA_2 FROM [foo]'`

What the query should look like
`An exception occurred while executing 'SELECT t0_.AA AS AA_0, t0_.BB AS BB_1, t0_.[12AA] AS "12AA_2" FROM [foo]'`

The code looks like this
```
$queryBuilder = $this->entityManager->createQueryBuilder();
$queryBuilder->select('a')->from(foo::class, 'a');
$list = $queryBuilder->getQuery()->getResult();
```

Is there any workaround for this?

**Comment by Ocramius** [comment] 2018-08-07 20:01
What ORM version are you on? I think this is already fixed by prefixing without numbers as start

**Comment by ostrolucky** [comment] 2018-08-07 20:34
Dupe of https://github.com/doctrine/doctrine2/issues/6965

**Comment by Ocramius** [comment] 2018-08-07 20:49
Closing as per @ostrolucky's findings

**Closed by Ocramius** 2018-08-07 20:49 UTC
Labels: Duplicate
