### ISSUE TITLE
Doctrine for a multi-db application and dynamic fields

### ISSUE THREAD

**Issue by amine-ini** [doctrine/doctrine2#11529] opened 2024-06-27 07:32 UTC
Hello everyone !
In our application we want to use a Doctrine. However, our application is multi-database (one database per client). And moreover the table columns are not fixed and identical between all the DBs. To say that from the Web interface they can add fields (by choosing the type) and they are created dynamically.
So can I use Doctrine for these two points mentioned above? If so do you have any leads I am stuck.
Thank you in advance for your help

**Comment by derrabus** [comment] 2024-06-27 07:42
Duplicate of #11530.

**Closed as not planned by derrabus** 2024-06-27 07:42 UTC
