### ISSUE TITLE
Allow to disable the identity map or override UnitOfWork

### ISSUE THREAD

**Issue by lazarchik** [doctrine/doctrine2#5606] opened 2016-01-12 05:57 UTC
Hello. I'm surprised nobody asked about this before.

When dealing with existing codebase and trying to migrate it to using Doctrine, it's hard to do that immediately, in one commit. A more realistic approach is to start using Doctrine for new classes/tables, and gradually move the rest of the classes and queries later.

The problem with that approach is that Doctrine's identity map assumes that all database writes happen through it. Consider the following code:

    $user = getUserWithDoctrine($user_id);
    // ...
    updateUserWithPdo($user_id, $new_user_fields);
    // ...
    $user2 = getUserWithDoctrine($user_id);

Doctrine's identity map won't know anything about the update query that was made directly using PDO and return the same object (without the latest changes). This is very counter-intuitive, especially if these reads and writes are situated in different parts of the codebase.

One workaround is to always clear the entity manager before executing read queries (methods like find(), etc.) However, that makes the code more bloated, as well as a bit slower.

Other concerns that have to do with identity mapping are increased memory usage and using stale data when rows are updated in the database by other scripts.

Hopefully by now I made my case that there's at least some situations where disabling identity map is beneficial. Even without it Doctrine has plenty of features to be extremely useful in projects.

Surprisingly, Doctrine currently provides no way of disabling the identity map or overriding UnitOfWork. Field $unitOfWork in the EntityManager class is private and has no setters. It gets set in EntityManager's constructor and it's always set to a new instance of \Doctrine\ORM\UnitOfWork (hardcoded).

Will appreciate your feedback!

**Comment by DHager** [comment] 2016-01-12 06:50
> Doctrine's identity map won't know anything about the update query that was made directly using PDO and return the same object (without the latest changes). This is very counter-intuitive, especially if these reads and writes are situated in different parts of the codebase.

I, uhm, don't see it as counter-intuitive at all. Doctrine is not some sort of binary plugin for your database which can "monitor" all changes happening on any table in real-time. Even if you hacked PHP's internals so that PDO somehow "reported" what it was doing, you'd *still* be sunk if a change was made by another PHP-process, another web-host, or even just some guy using PhpMyAdmin.

In short, your example scenario can never be done safely, so Doctrine was never designed to try.

> One workaround is to always clear the entity manager before executing read queries (methods like find(), etc.) However, that makes the code more bloated, as well as a bit slower.

I'm not sure that's a "workaround" as much as "the right thing to do": You've finished using doctrine for a unit-of-work, and you need to *tell it so*.

**Comment by lazarchik** [comment] 2016-01-12 07:17
Hi, DHager, thanks for responding.

> I'm not sure that's a "workaround" as much as "the right thing".

Is this what you're suggesting?

    $entityManager->clear();
    $user = $entityManager->find('User', 1234);

I can add a call to clear() before all find() calls in my code but it's more typing and less clean/readable code. And if we're always clearing the identity map before making find() calls, why use identity map in the first place? We can save a bunch of memory manipulations by not using the identity map.

> Doctrine is not some sort of binary plugin for your database which can "monitor" all changes happening on any table in real-time.

That's not what I was suggesting. Precisely because this is impossible, Doctrine should allow to bypass the identity map, i.e. if I'm trying to get the same row from the database for the second time, don't assume it haven't changed compared to the last time (as explain in item 10.1 here: http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/unitofwork.html).

**Comment by Ocramius** [comment] 2016-01-12 07:19
This is a duplicate of #5550.

**Closed by Ocramius** 2016-01-12 07:19 UTC

**Comment by ekonoval** [comment] 2018-03-28 18:42
@lzref what was the solution in this case for you? I also have a legacy project and try using Doctrine with legacy code (direct mysqli queries) and also experience the same problem.

**Comment by lzref** [comment] 2018-03-29 06:57
@ekonoval it's really ingrained into Doctrine's code and Doctrine provides no easy way to override stuff. Doctrine uses hardcoded class names in many places so even if you extend some classes it's hard to make Doctrine use them.

So what we ended up doing is just clearing entity manager cache before important reads or after writes. Mostly this situation doesn't happen that often in real life code (reading an entity, then modifying the DB row outside of doctrine, then reading it again within the same PHP request). This situation does happen quite often in our unit tests though (because each test creates DB records it needs), but we added an automatic clear() after we save stuff there.

**Comment by ekonoval** [comment] 2018-03-29 08:22
@lzref thanks for your reply! From your experience, would you recommend just use 
```
$entityManager->clear();
$user = $entityManager->find('User', 1234);
```
or

```
$entityManager->clear('User');
$user = $entityManager->find('User', 1234);
```

**Comment by Ocramius** [comment] 2018-03-29 12:30
> @ekonoval it's really ingrained into Doctrine's code and Doctrine provides no easy way to override stuff. Doctrine uses hardcoded class names in many places so even if you extend some classes it's hard to make Doctrine use them.

Not just that: the codebase is not designed with swappable components in mind, and that on purpose. As I've already highlighted, #5550 may provide what you are looking for.

@ekonoval please don't use `$entityManager->clear($entityName)`: we deprecated that for good reasons (see https://github.com/doctrine/doctrine2/issues/5855)

**Comment by ekonoval** [comment] 2018-03-29 12:44
@Ocramius thanks for explanation, though haven't seen the deprecation anywhere. And what about detach($entity) , is it cool to use it?

**Comment by Ocramius** [comment] 2018-03-29 13:17
> is it cool to use it?

No: it brings in many other problems, as described in the linked https://github.com/doctrine/doctrine2/issues/5855
