### ISSUE TITLE
Autoload error when following the Getting Started Guide

### ISSUE THREAD

**Issue by ThomasLandauer** [doctrine/doctrine2#7411] opened 2018-09-25 14:47 UTC
### Bug Report

When following the tutorial at https://www.doctrine-project.org/projects/doctrine-orm/en/current/tutorials/getting-started.html (i.e. doctrine2/docs/en/tutorials/getting-started.rst), at the step `vendor/bin/doctrine orm:schema-tool:create` I'm getting this error:

```bash
$ vendor/bin/doctrine orm:schema-tool:update

PHP Fatal error:  Uncaught Error: Class 'Doctrine\Common\Annotations\AnnotationRegistry' not found in vendor/doctrine/orm/lib/Doctrine/ORM/Configuration.php:152
Stack trace:
#0 vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(71): Doctrine\ORM\Configuration->newDefaultAnnotationDriver(Array, true)
#1 bootstrap.php(10): Doctrine\ORM\Tools\Setup::createAnnotationMetadataConfiguration(Array, true)
#2 cli-config.php(3): require_once('...')
#3 vendor/doctrine/orm/bin/doctrine.php(48): require('...')
#4 doctrine/orm/bin/doctrine(4): include('...')
#5 {main}
  thrown in vendor/doctrine/orm/lib/Doctrine/ORM/Configuration.php on line 152
```

**Comment by Ocramius** [comment] 2018-09-25 14:52
Did you run the composer installation? What's your config file looking like?

**Comment by ThomasLandauer** [comment] 2018-09-25 15:07
I really followed the tutorial.

> Did you run the composer installation?

Sure :-)

> What's your config file looking like?

Copied from https://www.doctrine-project.org/projects/doctrine-orm/en/current/tutorials/getting-started.html#project-setup

**Comment by Ocramius** [comment] 2018-09-25 15:17
Just tried it, and could reproduce the problem. The issue is that the `composer.json` in that documentation should be pointing at `doctrine/orm` `^2.6.2`: can you maybe send a patch?

**Comment by ThomasLandauer** [comment] 2018-09-25 15:51
Sure, see https://github.com/doctrine/doctrine2/pull/7412

**Comment by Majkl578** [comment] 2018-11-11 21:14
#7412 has been merged.

**Closed by Majkl578** 2018-11-11 21:14 UTC
Labels: Documentation
