### ISSUE TITLE
2.14.2: libxml errors after patch release update

### ISSUE THREAD

**Issue by ro0NL** [doctrine/doctrine2#10626] opened 2023-04-13 13:53 UTC
```
  - Upgrading doctrine/orm (2.14.1 => 2.14.2)
```

this PATCH release breaks our tree entities:

```
+ bin/console doctrine:migrations:migrate --allow-no-migration -v -n

In MappingException.php line 1005:
                                                                                                                                                                                              
  [Doctrine\ORM\Mapping\MappingException]                                                                                                                                                     
  libxml error: Element '{http://gediminasm.org/schemas/orm/doctrine-extensions-mapping}tree': No matching global element declaration available, but demanded by the strict wildcard.         
   in /app/config/doctrine/Entity.Some.orm.xml at line 18   
```

**Comment by greg0ire** [comment] 2023-04-13 14:04
Duplicate of https://github.com/doctrine/DoctrineBundle/issues/1643

**Closed as completed by greg0ire** 2023-04-13 14:04 UTC

**Comment by ro0NL** [comment] 2023-04-13 14:26
i guess. the breakage on our side was solely due `Upgrading doctrine/orm (2.14.1 => 2.14.2)`

**Comment by greg0ire** [comment] 2023-04-13 14:32
Kinda… it should have happened when upgrading doctrine bundle to 2.9, but didn't because of a bug [fixed in ORM 2.14.2](https://github.com/doctrine/orm/pull/10579)
