### ISSUE TITLE
Column defined as `enumType` throws type error when object hydration occurs.

### ISSUE THREAD

**Issue by CedrickOka** [doctrine/doctrine2#10078] opened 2022-09-29 10:20 UTC
### Bug Report

PHP 8.1 Enum Support

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.13.2

#### Summary

```php
$queryBuilder = $this->createQueryBuilder('e')
    ->getQuery()
    ->getResult(); // Throw TypeError exception: \BackedEnum::from(): Argument #1 ($value) must be of type string, \BackedEnum given
```

#### Current behavior

Column defined as `enumType` throws type error when object hydration occurs.

##### Define entity mappings 

```php
<?php
// App\Entity\Foo.php
namespace App\Entity;

use App\Enum\FooType;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 * @ORM\Table(name="foo")
 */
class Foo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     *
     * @var int
     */
    protected $id;

    /**
     * @ORM\Column(type="string", enumType="App\Enum\FooType", columnDefinition="ENUM('defaults', 'others')")
     *
     * @var FooType
     */
    protected $type;

//...
}
```

##### Execute query builder request

```php
$queryBuilder = $this->createQueryBuilder('f')
    ->from(\App\Entity\Foo::class, 'f')
    ->getQuery()
    ->getResult();
```

This query throw following exception

```sh
TypeError: App\Enum\Foo::from(): Argument #1 ($value) must be of type string, App\Enum\Foo given

.../vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ReflectionEnumProperty.php:93
.../vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ReflectionEnumProperty.php:77
.../vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ReflectionEmbeddedProperty.php:79
.../vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2745
.../vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php:266
.../vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php:492
.../vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php:148
.../vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php:270
.../vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:1224
.../vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:1165
.../vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:901
```

After analysis we think that it is the modification in the file `lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php` which is in question. It causes a double conversion of the enumeration a first time here:

```php
// \Doctrine\ORM\Internal\Hydration\AbstractHydrator::gatherRowData()
// From line 467 to 470
if ($value !== null && isset($cacheKeyInfo['enumType'])) {
  $value = $this->buildEnum($value, $cacheKeyInfo['enumType']);
}
```

And then here: 

```php
// \Doctrine\ORM\Internal\Hydration\ObjectHydrator::hydrateRowData()
// From line 492 to 493
$element = $this->getEntity($data, $dqlAlias);
```

#### Expected behavior

To be hydrated as php enum.

**Comment by derrabus** [comment] 2022-09-29 10:36
Duplicate of #10057

**Closed as not planned by derrabus** 2022-09-29 10:36 UTC
